/*
Account Management API

API for managing accounts in Saviynt/SSM. - **Create Account**: Creates a new account record. - **Update Account**: Updates an existing account based on its name. - **Export Account**: Retrieves all existing accounts for a given endpoint and security system. - **Get Account Details**: Returns a list of accounts based on search criteria. - **Assign Account to User**: Provisions an account to a user. - **Assign Entitlement to Account**: Provisions one or more entitlements to an account. - **Remove Entitlement from Account**: Deprovisions one or more entitlements from an account. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateAccount200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccount200Response{}

// CreateAccount200Response struct for CreateAccount200Response
type CreateAccount200Response struct {
	ErrorCode *string `json:"errorCode,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewCreateAccount200Response instantiates a new CreateAccount200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccount200Response() *CreateAccount200Response {
	this := CreateAccount200Response{}
	return &this
}

// NewCreateAccount200ResponseWithDefaults instantiates a new CreateAccount200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccount200ResponseWithDefaults() *CreateAccount200Response {
	this := CreateAccount200Response{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *CreateAccount200Response) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccount200Response) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *CreateAccount200Response) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *CreateAccount200Response) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateAccount200Response) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccount200Response) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateAccount200Response) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateAccount200Response) SetMessage(v string) {
	o.Message = &v
}

func (o CreateAccount200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccount200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCreateAccount200Response struct {
	value *CreateAccount200Response
	isSet bool
}

func (v NullableCreateAccount200Response) Get() *CreateAccount200Response {
	return v.value
}

func (v *NullableCreateAccount200Response) Set(val *CreateAccount200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccount200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccount200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccount200Response(val *CreateAccount200Response) *NullableCreateAccount200Response {
	return &NullableCreateAccount200Response{value: val, isSet: true}
}

func (v NullableCreateAccount200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccount200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


