/*
Account Management API

API for managing accounts in Saviynt/SSM. - **Create Account**: Creates a new account record. - **Update Account**: Updates an existing account based on its name. - **Export Account**: Retrieves all existing accounts for a given endpoint and security system. - **Get Account Details**: Returns a list of accounts based on search criteria. - **Assign Account to User**: Provisions an account to a user. - **Assign Entitlement to Account**: Provisions one or more entitlements to an account. - **Remove Entitlement from Account**: Deprovisions one or more entitlements from an account. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateAccountDefaultResponse type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateAccountDefaultResponse{}

// CreateAccountDefaultResponse struct for CreateAccountDefaultResponse
type CreateAccountDefaultResponse struct {
	ErrorCode *string `json:"errorCode,omitempty"`
	Message *string `json:"message,omitempty"`
}

// NewCreateAccountDefaultResponse instantiates a new CreateAccountDefaultResponse object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateAccountDefaultResponse() *CreateAccountDefaultResponse {
	this := CreateAccountDefaultResponse{}
	return &this
}

// NewCreateAccountDefaultResponseWithDefaults instantiates a new CreateAccountDefaultResponse object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateAccountDefaultResponseWithDefaults() *CreateAccountDefaultResponse {
	this := CreateAccountDefaultResponse{}
	return &this
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *CreateAccountDefaultResponse) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountDefaultResponse) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *CreateAccountDefaultResponse) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *CreateAccountDefaultResponse) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetMessage returns the Message field value if set, zero value otherwise.
func (o *CreateAccountDefaultResponse) GetMessage() string {
	if o == nil || IsNil(o.Message) {
		var ret string
		return ret
	}
	return *o.Message
}

// GetMessageOk returns a tuple with the Message field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateAccountDefaultResponse) GetMessageOk() (*string, bool) {
	if o == nil || IsNil(o.Message) {
		return nil, false
	}
	return o.Message, true
}

// HasMessage returns a boolean if a field has been set.
func (o *CreateAccountDefaultResponse) HasMessage() bool {
	if o != nil && !IsNil(o.Message) {
		return true
	}

	return false
}

// SetMessage gets a reference to the given string and assigns it to the Message field.
func (o *CreateAccountDefaultResponse) SetMessage(v string) {
	o.Message = &v
}

func (o CreateAccountDefaultResponse) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateAccountDefaultResponse) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if !IsNil(o.Message) {
		toSerialize["message"] = o.Message
	}
	return toSerialize, nil
}

type NullableCreateAccountDefaultResponse struct {
	value *CreateAccountDefaultResponse
	isSet bool
}

func (v NullableCreateAccountDefaultResponse) Get() *CreateAccountDefaultResponse {
	return v.value
}

func (v *NullableCreateAccountDefaultResponse) Set(val *CreateAccountDefaultResponse) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateAccountDefaultResponse) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateAccountDefaultResponse) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateAccountDefaultResponse(val *CreateAccountDefaultResponse) *NullableCreateAccountDefaultResponse {
	return &NullableCreateAccountDefaultResponse{value: val, isSet: true}
}

func (v NullableCreateAccountDefaultResponse) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateAccountDefaultResponse) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


