/*
Account Management API

API for managing accounts in Saviynt/SSM. - **Create Account**: Creates a new account record. - **Update Account**: Updates an existing account based on its name. - **Export Account**: Retrieves all existing accounts for a given endpoint and security system. - **Get Account Details**: Returns a list of accounts based on search criteria. - **Assign Account to User**: Provisions an account to a user. - **Assign Entitlement to Account**: Provisions one or more entitlements to an account. - **Remove Entitlement from Account**: Deprovisions one or more entitlements from an account. 

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the UpdateAccountRequestAccountownerInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateAccountRequestAccountownerInner{}

// UpdateAccountRequestAccountownerInner struct for UpdateAccountRequestAccountownerInner
type UpdateAccountRequestAccountownerInner struct {
	// Owner type (user or usergroup).
	Type string `json:"type"`
	// Username or usergroup name.
	Value string `json:"value"`
	// Optional rank. Allowed values: '1'-'5', '26' (for primary certifier), '27' (for secondary certifier).
	Rank *string `json:"rank,omitempty"`
	// Action to perform, either 'add' or 'remove'.
	Action string `json:"action"`
}

type _UpdateAccountRequestAccountownerInner UpdateAccountRequestAccountownerInner

// NewUpdateAccountRequestAccountownerInner instantiates a new UpdateAccountRequestAccountownerInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateAccountRequestAccountownerInner(type_ string, value string, action string) *UpdateAccountRequestAccountownerInner {
	this := UpdateAccountRequestAccountownerInner{}
	this.Type = type_
	this.Value = value
	this.Action = action
	return &this
}

// NewUpdateAccountRequestAccountownerInnerWithDefaults instantiates a new UpdateAccountRequestAccountownerInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateAccountRequestAccountownerInnerWithDefaults() *UpdateAccountRequestAccountownerInner {
	this := UpdateAccountRequestAccountownerInner{}
	return &this
}

// GetType returns the Type field value
func (o *UpdateAccountRequestAccountownerInner) GetType() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Type
}

// GetTypeOk returns a tuple with the Type field value
// and a boolean to check if the value has been set.
func (o *UpdateAccountRequestAccountownerInner) GetTypeOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Type, true
}

// SetType sets field value
func (o *UpdateAccountRequestAccountownerInner) SetType(v string) {
	o.Type = v
}

// GetValue returns the Value field value
func (o *UpdateAccountRequestAccountownerInner) GetValue() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Value
}

// GetValueOk returns a tuple with the Value field value
// and a boolean to check if the value has been set.
func (o *UpdateAccountRequestAccountownerInner) GetValueOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Value, true
}

// SetValue sets field value
func (o *UpdateAccountRequestAccountownerInner) SetValue(v string) {
	o.Value = v
}

// GetRank returns the Rank field value if set, zero value otherwise.
func (o *UpdateAccountRequestAccountownerInner) GetRank() string {
	if o == nil || IsNil(o.Rank) {
		var ret string
		return ret
	}
	return *o.Rank
}

// GetRankOk returns a tuple with the Rank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateAccountRequestAccountownerInner) GetRankOk() (*string, bool) {
	if o == nil || IsNil(o.Rank) {
		return nil, false
	}
	return o.Rank, true
}

// HasRank returns a boolean if a field has been set.
func (o *UpdateAccountRequestAccountownerInner) HasRank() bool {
	if o != nil && !IsNil(o.Rank) {
		return true
	}

	return false
}

// SetRank gets a reference to the given string and assigns it to the Rank field.
func (o *UpdateAccountRequestAccountownerInner) SetRank(v string) {
	o.Rank = &v
}

// GetAction returns the Action field value
func (o *UpdateAccountRequestAccountownerInner) GetAction() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Action
}

// GetActionOk returns a tuple with the Action field value
// and a boolean to check if the value has been set.
func (o *UpdateAccountRequestAccountownerInner) GetActionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Action, true
}

// SetAction sets field value
func (o *UpdateAccountRequestAccountownerInner) SetAction(v string) {
	o.Action = v
}

func (o UpdateAccountRequestAccountownerInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateAccountRequestAccountownerInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["type"] = o.Type
	toSerialize["value"] = o.Value
	if !IsNil(o.Rank) {
		toSerialize["rank"] = o.Rank
	}
	toSerialize["action"] = o.Action
	return toSerialize, nil
}

func (o *UpdateAccountRequestAccountownerInner) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"type",
		"value",
		"action",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varUpdateAccountRequestAccountownerInner := _UpdateAccountRequestAccountownerInner{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varUpdateAccountRequestAccountownerInner)

	if err != nil {
		return err
	}

	*o = UpdateAccountRequestAccountownerInner(varUpdateAccountRequestAccountownerInner)

	return err
}

type NullableUpdateAccountRequestAccountownerInner struct {
	value *UpdateAccountRequestAccountownerInner
	isSet bool
}

func (v NullableUpdateAccountRequestAccountownerInner) Get() *UpdateAccountRequestAccountownerInner {
	return v.value
}

func (v *NullableUpdateAccountRequestAccountownerInner) Set(val *UpdateAccountRequestAccountownerInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateAccountRequestAccountownerInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateAccountRequestAccountownerInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateAccountRequestAccountownerInner(val *UpdateAccountRequestAccountownerInner) *NullableUpdateAccountRequestAccountownerInner {
	return &NullableUpdateAccountRequestAccountownerInner{value: val, isSet: true}
}

func (v NullableUpdateAccountRequestAccountownerInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateAccountRequestAccountownerInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


