/*
Saviynt Connections API

Testing ConnectionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package test

import (
	"context"
	"log"
	"strings"
	"testing"

	"github.com/saviynt/saviynt-api-go-client/connections"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_connections_ConnectionsAPIService(t *testing.T) {
	apiClient, _, skipTests, skipMsg, err := client()
	require.Nil(t, err)

	ctx := context.Background()

	t.Run("Test ConnectionsAPIService TestConnection", func(t *testing.T) {
		if skipTests && strings.TrimSpace(skipMsg) != "" {
			t.Skip(skipMsg)
		} else if skipTests {
			t.Skip(MsgSkipTest)
		}

		data := "3752"
		req := connections.GetConnectionDetailsRequest{
			Connectionkey: &data,
		}
		resp, httpRes, err := apiClient.Connections.GetConnectionDetails(ctx).GetConnectionDetailsRequest(req).Execute()
		if err != nil {
			log.Fatalf("API error: %v", err.Error())
		}

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})
}
