/*
Saviynt SAV Roles API

Testing SAVRolesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package test

import (
	"context"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_savroles_SAVRolesAPIService(t *testing.T) {
	apiClient, wantTest, err := client()
	require.Nil(t, err)

	t.Run("Test SAVRolesAPIService GetAllSAVRoles", func(t *testing.T) {
		if !wantTest {
			t.Skip("skip test") // remove to run test
		}

		resp, httpRes, err := apiClient.SAVRolesAPI.GetAllSAVRoles(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
		assert.Greater(t, len(resp.Savroles), 0)
	})

	t.Run("Test SAVRolesAPIService GetSAVRoleUsers", func(t *testing.T) {
		if !wantTest {
			t.Skip("skip test") // remove to run test
		}

		savRoleName := "ROLE_ADMIN"

		apiReq := apiClient.SAVRolesAPI.GetSAVRoleUsers(context.Background(), savRoleName)
		apiReq = apiReq.Limit("100")
		apiReq = apiReq.Offset("0")

		resp, httpRes, err := apiReq.Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
		assert.Greater(t, len(resp.Users), 0)
	})
}
