/*
Saviynt Delegated Administration API

Testing DelegatedAdministrationAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package test

import (
	"context"
	"testing"

	"github.com/grokify/saviynt-api-go-client/delegatedadministration"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_delegatedadministration_DelegatedAdministrationAPIService(t *testing.T) {
	apiClient, creds, wantTest, err := client()
	require.Nil(t, err)

	t.Run("Test DelegatedAdministrationAPIService CreateDelegate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DelegatedAdministrationAPI.CreateDelegate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DelegatedAdministrationAPIService DeleteDelegate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DelegatedAdministrationAPI.DeleteDelegate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DelegatedAdministrationAPIService EditDelegate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DelegatedAdministrationAPI.EditDelegate(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test DelegatedAdministrationAPIService FetchDelegatesList", func(t *testing.T) {
		if !wantTest {
			t.Skip("skip test") // remove to run test
		}

		req := delegatedadministration.FetchDelegatesListRequest{
			UserName: creds.Username,
		}

		apiReq := apiClient.DelegatedAdministrationAPI.FetchDelegatesList(context.Background())
		apiReq = apiReq.FetchDelegatesListRequest(req)

		resp, httpRes, err := apiReq.Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
		assert.Equal(t, "0", resp.ErrorCode)
	})

	t.Run("Test DelegatedAdministrationAPIService GetDelegateUserList", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.DelegatedAdministrationAPI.GetDelegateUserList(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
