/*
Saviynt Transport API

Testing TransportAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package test

import (
	"context"
	"path/filepath"
	"testing"
	"time"

	saviyntapigoclient "github.com/grokify/saviynt-api-go-client"
	"github.com/grokify/saviynt-api-go-client/transport"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_transport_TransportAPIService(t *testing.T) {
	apiClient, creds, wantTest, err := client()
	require.Nil(t, err)

	exportFilepath := "/saviynt_shared/testexport/transportPackage"
	var exportFilename string

	t.Run("Test TransportAPIService ExportTransportPackage", func(t *testing.T) {
		if !wantTest {
			t.Skip("skip test") // remove to run test
		}

		req := transport.ExportTransportPackageRequest{
			Updateuser:       &creds.Username,
			Transportowner:   saviyntapigoclient.Pointer("true"),
			Transportmembers: saviyntapigoclient.Pointer("true"),
			Exportonline:     "false",
			Exportpath:       &exportFilepath,
			Objectstoexport: transport.ObjectsToExport{
				SavRoles: []string{"ROLE_ADMIN"},
				EmailTemplate: []string{
					"Account Password Expiry Email",
					"Entitlement Expiry Email",
				},
			},
			Businessjustification: saviyntapigoclient.Pointer("justified..."),
		}
		apiReq := apiClient.TransportAPI.ExportTransportPackage(context.Background())
		apiReq = apiReq.ExportTransportPackageRequest(req)
		resp, httpRes, err := apiReq.Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
		assert.Equal(t, int32(0), resp.Errorcode)

		exportFilename = resp.FileName
		time.Sleep(25 * time.Second)
	})

	t.Run("Test TransportAPIService ImportTransportPackage", func(t *testing.T) {
		if !wantTest && exportFilename != "" {
			t.Skip("skip test") // remove to run test
		}

		req := transport.ImportTransportPackageRequest{
			Packagetoimport: filepath.Join(exportFilepath, exportFilename)}
		apiReq := apiClient.TransportAPI.ImportTransportPackage(context.Background())
		apiReq = apiReq.ImportTransportPackageRequest(req)
		resp, httpRes, err := apiReq.Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
		assert.Equal(t, int32(0), resp.Errorcode)
	})

	t.Run("Test TransportAPIService TransportPackageStatus", func(t *testing.T) {
		if !wantTest {
			t.Skip("skip test") // remove to run test
		}

		req := transport.TransportPackageStatusRequest{
			Operation: "export",
			Filename:  exportFilename}

		apiReq := apiClient.TransportAPI.TransportPackageStatus(context.Background())
		apiReq = apiReq.TransportPackageStatusRequest(req)
		resp, httpRes, err := apiReq.Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
		assert.Equal(t, int32(0), resp.ErrorCode)
	})
}
