/*
Saviynt SAV Roles API

Saviynt SAV Roles API

API version: 1.0
Contact: https://github.com/saviynt
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package savroles

import (
	"encoding/json"
)

// checks if the SAVRole type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SAVRole{}

// SAVRole struct for SAVRole
type SAVRole struct {
	UPDATEUSER       *string `json:"UPDATEUSER,omitempty"`
	CUSTOMPROPERTY20 *string `json:"CUSTOMPROPERTY20,omitempty"`
	ROLENAME         *string `json:"ROLENAME,omitempty"`
	HOMEPAGE         *string `json:"HOMEPAGE,omitempty"`
	CUSTOMPROPERTY10 *string `json:"CUSTOMPROPERTY10,omitempty"`
	CUSTOMPROPERTY12 *string `json:"CUSTOMPROPERTY12,omitempty"`
	CUSTOMPROPERTY11 *string `json:"CUSTOMPROPERTY11,omitempty"`
	CUSTOMPROPERTY14 *string `json:"CUSTOMPROPERTY14,omitempty"`
	CUSTOMPROPERTY4  *string `json:"CUSTOMPROPERTY4,omitempty"`
	CUSTOMPROPERTY13 *string `json:"CUSTOMPROPERTY13,omitempty"`
	CUSTOMPROPERTY5  *string `json:"CUSTOMPROPERTY5,omitempty"`
	CUSTOMPROPERTY16 *string `json:"CUSTOMPROPERTY16,omitempty"`
	CUSTOMPROPERTY2  *string `json:"CUSTOMPROPERTY2,omitempty"`
	CUSTOMPROPERTY15 *string `json:"CUSTOMPROPERTY15,omitempty"`
	CUSTOMPROPERTY3  *string `json:"CUSTOMPROPERTY3,omitempty"`
	CUSTOMPROPERTY18 *string `json:"CUSTOMPROPERTY18,omitempty"`
	CUSTOMPROPERTY1  *string `json:"CUSTOMPROPERTY1,omitempty"`
	CUSTOMPROPERTY17 *string `json:"CUSTOMPROPERTY17,omitempty"`
	ROLEDESCRIPTION  *string `json:"ROLEDESCRIPTION,omitempty"`
	CUSTOMPROPERTY19 *string `json:"CUSTOMPROPERTY19,omitempty"`
	ISOOTB           *string `json:"ISOOTB,omitempty"`
	CUSTOMPROPERTY8  *string `json:"CUSTOMPROPERTY8,omitempty"`
	CUSTOMPROPERTY9  *string `json:"CUSTOMPROPERTY9,omitempty"`
	CUSTOMPROPERTY6  *string `json:"CUSTOMPROPERTY6,omitempty"`
	CUSTOMPROPERTY7  *string `json:"CUSTOMPROPERTY7,omitempty"`
	UPDATEDATE       *string `json:"UPDATEDATE,omitempty"`
	READONLY         *string `json:"READONLY,omitempty"`
	STATUSKEY        *string `json:"STATUSKEY,omitempty"`
}

// NewSAVRole instantiates a new SAVRole object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSAVRole() *SAVRole {
	this := SAVRole{}
	return &this
}

// NewSAVRoleWithDefaults instantiates a new SAVRole object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSAVRoleWithDefaults() *SAVRole {
	this := SAVRole{}
	return &this
}

// GetUPDATEUSER returns the UPDATEUSER field value if set, zero value otherwise.
func (o *SAVRole) GetUPDATEUSER() string {
	if o == nil || IsNil(o.UPDATEUSER) {
		var ret string
		return ret
	}
	return *o.UPDATEUSER
}

// GetUPDATEUSEROk returns a tuple with the UPDATEUSER field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetUPDATEUSEROk() (*string, bool) {
	if o == nil || IsNil(o.UPDATEUSER) {
		return nil, false
	}
	return o.UPDATEUSER, true
}

// HasUPDATEUSER returns a boolean if a field has been set.
func (o *SAVRole) HasUPDATEUSER() bool {
	if o != nil && !IsNil(o.UPDATEUSER) {
		return true
	}

	return false
}

// SetUPDATEUSER gets a reference to the given string and assigns it to the UPDATEUSER field.
func (o *SAVRole) SetUPDATEUSER(v string) {
	o.UPDATEUSER = &v
}

// GetCUSTOMPROPERTY20 returns the CUSTOMPROPERTY20 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY20() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY20) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY20
}

// GetCUSTOMPROPERTY20Ok returns a tuple with the CUSTOMPROPERTY20 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY20Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY20) {
		return nil, false
	}
	return o.CUSTOMPROPERTY20, true
}

// HasCUSTOMPROPERTY20 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY20() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY20) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY20 gets a reference to the given string and assigns it to the CUSTOMPROPERTY20 field.
func (o *SAVRole) SetCUSTOMPROPERTY20(v string) {
	o.CUSTOMPROPERTY20 = &v
}

// GetROLENAME returns the ROLENAME field value if set, zero value otherwise.
func (o *SAVRole) GetROLENAME() string {
	if o == nil || IsNil(o.ROLENAME) {
		var ret string
		return ret
	}
	return *o.ROLENAME
}

// GetROLENAMEOk returns a tuple with the ROLENAME field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetROLENAMEOk() (*string, bool) {
	if o == nil || IsNil(o.ROLENAME) {
		return nil, false
	}
	return o.ROLENAME, true
}

// HasROLENAME returns a boolean if a field has been set.
func (o *SAVRole) HasROLENAME() bool {
	if o != nil && !IsNil(o.ROLENAME) {
		return true
	}

	return false
}

// SetROLENAME gets a reference to the given string and assigns it to the ROLENAME field.
func (o *SAVRole) SetROLENAME(v string) {
	o.ROLENAME = &v
}

// GetHOMEPAGE returns the HOMEPAGE field value if set, zero value otherwise.
func (o *SAVRole) GetHOMEPAGE() string {
	if o == nil || IsNil(o.HOMEPAGE) {
		var ret string
		return ret
	}
	return *o.HOMEPAGE
}

// GetHOMEPAGEOk returns a tuple with the HOMEPAGE field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetHOMEPAGEOk() (*string, bool) {
	if o == nil || IsNil(o.HOMEPAGE) {
		return nil, false
	}
	return o.HOMEPAGE, true
}

// HasHOMEPAGE returns a boolean if a field has been set.
func (o *SAVRole) HasHOMEPAGE() bool {
	if o != nil && !IsNil(o.HOMEPAGE) {
		return true
	}

	return false
}

// SetHOMEPAGE gets a reference to the given string and assigns it to the HOMEPAGE field.
func (o *SAVRole) SetHOMEPAGE(v string) {
	o.HOMEPAGE = &v
}

// GetCUSTOMPROPERTY10 returns the CUSTOMPROPERTY10 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY10() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY10) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY10
}

// GetCUSTOMPROPERTY10Ok returns a tuple with the CUSTOMPROPERTY10 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY10Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY10) {
		return nil, false
	}
	return o.CUSTOMPROPERTY10, true
}

// HasCUSTOMPROPERTY10 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY10() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY10) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY10 gets a reference to the given string and assigns it to the CUSTOMPROPERTY10 field.
func (o *SAVRole) SetCUSTOMPROPERTY10(v string) {
	o.CUSTOMPROPERTY10 = &v
}

// GetCUSTOMPROPERTY12 returns the CUSTOMPROPERTY12 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY12() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY12) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY12
}

// GetCUSTOMPROPERTY12Ok returns a tuple with the CUSTOMPROPERTY12 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY12Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY12) {
		return nil, false
	}
	return o.CUSTOMPROPERTY12, true
}

// HasCUSTOMPROPERTY12 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY12() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY12) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY12 gets a reference to the given string and assigns it to the CUSTOMPROPERTY12 field.
func (o *SAVRole) SetCUSTOMPROPERTY12(v string) {
	o.CUSTOMPROPERTY12 = &v
}

// GetCUSTOMPROPERTY11 returns the CUSTOMPROPERTY11 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY11() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY11) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY11
}

// GetCUSTOMPROPERTY11Ok returns a tuple with the CUSTOMPROPERTY11 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY11Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY11) {
		return nil, false
	}
	return o.CUSTOMPROPERTY11, true
}

// HasCUSTOMPROPERTY11 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY11() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY11) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY11 gets a reference to the given string and assigns it to the CUSTOMPROPERTY11 field.
func (o *SAVRole) SetCUSTOMPROPERTY11(v string) {
	o.CUSTOMPROPERTY11 = &v
}

// GetCUSTOMPROPERTY14 returns the CUSTOMPROPERTY14 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY14() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY14) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY14
}

// GetCUSTOMPROPERTY14Ok returns a tuple with the CUSTOMPROPERTY14 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY14Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY14) {
		return nil, false
	}
	return o.CUSTOMPROPERTY14, true
}

// HasCUSTOMPROPERTY14 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY14() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY14) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY14 gets a reference to the given string and assigns it to the CUSTOMPROPERTY14 field.
func (o *SAVRole) SetCUSTOMPROPERTY14(v string) {
	o.CUSTOMPROPERTY14 = &v
}

// GetCUSTOMPROPERTY4 returns the CUSTOMPROPERTY4 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY4() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY4) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY4
}

// GetCUSTOMPROPERTY4Ok returns a tuple with the CUSTOMPROPERTY4 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY4Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY4) {
		return nil, false
	}
	return o.CUSTOMPROPERTY4, true
}

// HasCUSTOMPROPERTY4 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY4() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY4) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY4 gets a reference to the given string and assigns it to the CUSTOMPROPERTY4 field.
func (o *SAVRole) SetCUSTOMPROPERTY4(v string) {
	o.CUSTOMPROPERTY4 = &v
}

// GetCUSTOMPROPERTY13 returns the CUSTOMPROPERTY13 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY13() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY13) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY13
}

// GetCUSTOMPROPERTY13Ok returns a tuple with the CUSTOMPROPERTY13 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY13Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY13) {
		return nil, false
	}
	return o.CUSTOMPROPERTY13, true
}

// HasCUSTOMPROPERTY13 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY13() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY13) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY13 gets a reference to the given string and assigns it to the CUSTOMPROPERTY13 field.
func (o *SAVRole) SetCUSTOMPROPERTY13(v string) {
	o.CUSTOMPROPERTY13 = &v
}

// GetCUSTOMPROPERTY5 returns the CUSTOMPROPERTY5 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY5() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY5) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY5
}

// GetCUSTOMPROPERTY5Ok returns a tuple with the CUSTOMPROPERTY5 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY5Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY5) {
		return nil, false
	}
	return o.CUSTOMPROPERTY5, true
}

// HasCUSTOMPROPERTY5 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY5() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY5) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY5 gets a reference to the given string and assigns it to the CUSTOMPROPERTY5 field.
func (o *SAVRole) SetCUSTOMPROPERTY5(v string) {
	o.CUSTOMPROPERTY5 = &v
}

// GetCUSTOMPROPERTY16 returns the CUSTOMPROPERTY16 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY16() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY16) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY16
}

// GetCUSTOMPROPERTY16Ok returns a tuple with the CUSTOMPROPERTY16 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY16Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY16) {
		return nil, false
	}
	return o.CUSTOMPROPERTY16, true
}

// HasCUSTOMPROPERTY16 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY16() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY16) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY16 gets a reference to the given string and assigns it to the CUSTOMPROPERTY16 field.
func (o *SAVRole) SetCUSTOMPROPERTY16(v string) {
	o.CUSTOMPROPERTY16 = &v
}

// GetCUSTOMPROPERTY2 returns the CUSTOMPROPERTY2 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY2() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY2) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY2
}

// GetCUSTOMPROPERTY2Ok returns a tuple with the CUSTOMPROPERTY2 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY2Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY2) {
		return nil, false
	}
	return o.CUSTOMPROPERTY2, true
}

// HasCUSTOMPROPERTY2 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY2() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY2) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY2 gets a reference to the given string and assigns it to the CUSTOMPROPERTY2 field.
func (o *SAVRole) SetCUSTOMPROPERTY2(v string) {
	o.CUSTOMPROPERTY2 = &v
}

// GetCUSTOMPROPERTY15 returns the CUSTOMPROPERTY15 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY15() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY15) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY15
}

// GetCUSTOMPROPERTY15Ok returns a tuple with the CUSTOMPROPERTY15 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY15Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY15) {
		return nil, false
	}
	return o.CUSTOMPROPERTY15, true
}

// HasCUSTOMPROPERTY15 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY15() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY15) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY15 gets a reference to the given string and assigns it to the CUSTOMPROPERTY15 field.
func (o *SAVRole) SetCUSTOMPROPERTY15(v string) {
	o.CUSTOMPROPERTY15 = &v
}

// GetCUSTOMPROPERTY3 returns the CUSTOMPROPERTY3 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY3() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY3) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY3
}

// GetCUSTOMPROPERTY3Ok returns a tuple with the CUSTOMPROPERTY3 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY3Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY3) {
		return nil, false
	}
	return o.CUSTOMPROPERTY3, true
}

// HasCUSTOMPROPERTY3 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY3() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY3) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY3 gets a reference to the given string and assigns it to the CUSTOMPROPERTY3 field.
func (o *SAVRole) SetCUSTOMPROPERTY3(v string) {
	o.CUSTOMPROPERTY3 = &v
}

// GetCUSTOMPROPERTY18 returns the CUSTOMPROPERTY18 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY18() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY18) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY18
}

// GetCUSTOMPROPERTY18Ok returns a tuple with the CUSTOMPROPERTY18 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY18Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY18) {
		return nil, false
	}
	return o.CUSTOMPROPERTY18, true
}

// HasCUSTOMPROPERTY18 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY18() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY18) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY18 gets a reference to the given string and assigns it to the CUSTOMPROPERTY18 field.
func (o *SAVRole) SetCUSTOMPROPERTY18(v string) {
	o.CUSTOMPROPERTY18 = &v
}

// GetCUSTOMPROPERTY1 returns the CUSTOMPROPERTY1 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY1() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY1) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY1
}

// GetCUSTOMPROPERTY1Ok returns a tuple with the CUSTOMPROPERTY1 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY1Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY1) {
		return nil, false
	}
	return o.CUSTOMPROPERTY1, true
}

// HasCUSTOMPROPERTY1 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY1() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY1) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY1 gets a reference to the given string and assigns it to the CUSTOMPROPERTY1 field.
func (o *SAVRole) SetCUSTOMPROPERTY1(v string) {
	o.CUSTOMPROPERTY1 = &v
}

// GetCUSTOMPROPERTY17 returns the CUSTOMPROPERTY17 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY17() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY17) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY17
}

// GetCUSTOMPROPERTY17Ok returns a tuple with the CUSTOMPROPERTY17 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY17Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY17) {
		return nil, false
	}
	return o.CUSTOMPROPERTY17, true
}

// HasCUSTOMPROPERTY17 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY17() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY17) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY17 gets a reference to the given string and assigns it to the CUSTOMPROPERTY17 field.
func (o *SAVRole) SetCUSTOMPROPERTY17(v string) {
	o.CUSTOMPROPERTY17 = &v
}

// GetROLEDESCRIPTION returns the ROLEDESCRIPTION field value if set, zero value otherwise.
func (o *SAVRole) GetROLEDESCRIPTION() string {
	if o == nil || IsNil(o.ROLEDESCRIPTION) {
		var ret string
		return ret
	}
	return *o.ROLEDESCRIPTION
}

// GetROLEDESCRIPTIONOk returns a tuple with the ROLEDESCRIPTION field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetROLEDESCRIPTIONOk() (*string, bool) {
	if o == nil || IsNil(o.ROLEDESCRIPTION) {
		return nil, false
	}
	return o.ROLEDESCRIPTION, true
}

// HasROLEDESCRIPTION returns a boolean if a field has been set.
func (o *SAVRole) HasROLEDESCRIPTION() bool {
	if o != nil && !IsNil(o.ROLEDESCRIPTION) {
		return true
	}

	return false
}

// SetROLEDESCRIPTION gets a reference to the given string and assigns it to the ROLEDESCRIPTION field.
func (o *SAVRole) SetROLEDESCRIPTION(v string) {
	o.ROLEDESCRIPTION = &v
}

// GetCUSTOMPROPERTY19 returns the CUSTOMPROPERTY19 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY19() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY19) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY19
}

// GetCUSTOMPROPERTY19Ok returns a tuple with the CUSTOMPROPERTY19 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY19Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY19) {
		return nil, false
	}
	return o.CUSTOMPROPERTY19, true
}

// HasCUSTOMPROPERTY19 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY19() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY19) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY19 gets a reference to the given string and assigns it to the CUSTOMPROPERTY19 field.
func (o *SAVRole) SetCUSTOMPROPERTY19(v string) {
	o.CUSTOMPROPERTY19 = &v
}

// GetISOOTB returns the ISOOTB field value if set, zero value otherwise.
func (o *SAVRole) GetISOOTB() string {
	if o == nil || IsNil(o.ISOOTB) {
		var ret string
		return ret
	}
	return *o.ISOOTB
}

// GetISOOTBOk returns a tuple with the ISOOTB field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetISOOTBOk() (*string, bool) {
	if o == nil || IsNil(o.ISOOTB) {
		return nil, false
	}
	return o.ISOOTB, true
}

// HasISOOTB returns a boolean if a field has been set.
func (o *SAVRole) HasISOOTB() bool {
	if o != nil && !IsNil(o.ISOOTB) {
		return true
	}

	return false
}

// SetISOOTB gets a reference to the given string and assigns it to the ISOOTB field.
func (o *SAVRole) SetISOOTB(v string) {
	o.ISOOTB = &v
}

// GetCUSTOMPROPERTY8 returns the CUSTOMPROPERTY8 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY8() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY8) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY8
}

// GetCUSTOMPROPERTY8Ok returns a tuple with the CUSTOMPROPERTY8 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY8Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY8) {
		return nil, false
	}
	return o.CUSTOMPROPERTY8, true
}

// HasCUSTOMPROPERTY8 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY8() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY8) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY8 gets a reference to the given string and assigns it to the CUSTOMPROPERTY8 field.
func (o *SAVRole) SetCUSTOMPROPERTY8(v string) {
	o.CUSTOMPROPERTY8 = &v
}

// GetCUSTOMPROPERTY9 returns the CUSTOMPROPERTY9 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY9() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY9) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY9
}

// GetCUSTOMPROPERTY9Ok returns a tuple with the CUSTOMPROPERTY9 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY9Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY9) {
		return nil, false
	}
	return o.CUSTOMPROPERTY9, true
}

// HasCUSTOMPROPERTY9 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY9() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY9) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY9 gets a reference to the given string and assigns it to the CUSTOMPROPERTY9 field.
func (o *SAVRole) SetCUSTOMPROPERTY9(v string) {
	o.CUSTOMPROPERTY9 = &v
}

// GetCUSTOMPROPERTY6 returns the CUSTOMPROPERTY6 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY6() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY6) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY6
}

// GetCUSTOMPROPERTY6Ok returns a tuple with the CUSTOMPROPERTY6 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY6Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY6) {
		return nil, false
	}
	return o.CUSTOMPROPERTY6, true
}

// HasCUSTOMPROPERTY6 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY6() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY6) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY6 gets a reference to the given string and assigns it to the CUSTOMPROPERTY6 field.
func (o *SAVRole) SetCUSTOMPROPERTY6(v string) {
	o.CUSTOMPROPERTY6 = &v
}

// GetCUSTOMPROPERTY7 returns the CUSTOMPROPERTY7 field value if set, zero value otherwise.
func (o *SAVRole) GetCUSTOMPROPERTY7() string {
	if o == nil || IsNil(o.CUSTOMPROPERTY7) {
		var ret string
		return ret
	}
	return *o.CUSTOMPROPERTY7
}

// GetCUSTOMPROPERTY7Ok returns a tuple with the CUSTOMPROPERTY7 field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetCUSTOMPROPERTY7Ok() (*string, bool) {
	if o == nil || IsNil(o.CUSTOMPROPERTY7) {
		return nil, false
	}
	return o.CUSTOMPROPERTY7, true
}

// HasCUSTOMPROPERTY7 returns a boolean if a field has been set.
func (o *SAVRole) HasCUSTOMPROPERTY7() bool {
	if o != nil && !IsNil(o.CUSTOMPROPERTY7) {
		return true
	}

	return false
}

// SetCUSTOMPROPERTY7 gets a reference to the given string and assigns it to the CUSTOMPROPERTY7 field.
func (o *SAVRole) SetCUSTOMPROPERTY7(v string) {
	o.CUSTOMPROPERTY7 = &v
}

// GetUPDATEDATE returns the UPDATEDATE field value if set, zero value otherwise.
func (o *SAVRole) GetUPDATEDATE() string {
	if o == nil || IsNil(o.UPDATEDATE) {
		var ret string
		return ret
	}
	return *o.UPDATEDATE
}

// GetUPDATEDATEOk returns a tuple with the UPDATEDATE field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetUPDATEDATEOk() (*string, bool) {
	if o == nil || IsNil(o.UPDATEDATE) {
		return nil, false
	}
	return o.UPDATEDATE, true
}

// HasUPDATEDATE returns a boolean if a field has been set.
func (o *SAVRole) HasUPDATEDATE() bool {
	if o != nil && !IsNil(o.UPDATEDATE) {
		return true
	}

	return false
}

// SetUPDATEDATE gets a reference to the given string and assigns it to the UPDATEDATE field.
func (o *SAVRole) SetUPDATEDATE(v string) {
	o.UPDATEDATE = &v
}

// GetREADONLY returns the READONLY field value if set, zero value otherwise.
func (o *SAVRole) GetREADONLY() string {
	if o == nil || IsNil(o.READONLY) {
		var ret string
		return ret
	}
	return *o.READONLY
}

// GetREADONLYOk returns a tuple with the READONLY field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetREADONLYOk() (*string, bool) {
	if o == nil || IsNil(o.READONLY) {
		return nil, false
	}
	return o.READONLY, true
}

// HasREADONLY returns a boolean if a field has been set.
func (o *SAVRole) HasREADONLY() bool {
	if o != nil && !IsNil(o.READONLY) {
		return true
	}

	return false
}

// SetREADONLY gets a reference to the given string and assigns it to the READONLY field.
func (o *SAVRole) SetREADONLY(v string) {
	o.READONLY = &v
}

// GetSTATUSKEY returns the STATUSKEY field value if set, zero value otherwise.
func (o *SAVRole) GetSTATUSKEY() string {
	if o == nil || IsNil(o.STATUSKEY) {
		var ret string
		return ret
	}
	return *o.STATUSKEY
}

// GetSTATUSKEYOk returns a tuple with the STATUSKEY field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SAVRole) GetSTATUSKEYOk() (*string, bool) {
	if o == nil || IsNil(o.STATUSKEY) {
		return nil, false
	}
	return o.STATUSKEY, true
}

// HasSTATUSKEY returns a boolean if a field has been set.
func (o *SAVRole) HasSTATUSKEY() bool {
	if o != nil && !IsNil(o.STATUSKEY) {
		return true
	}

	return false
}

// SetSTATUSKEY gets a reference to the given string and assigns it to the STATUSKEY field.
func (o *SAVRole) SetSTATUSKEY(v string) {
	o.STATUSKEY = &v
}

func (o SAVRole) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SAVRole) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.UPDATEUSER) {
		toSerialize["UPDATEUSER"] = o.UPDATEUSER
	}
	if !IsNil(o.CUSTOMPROPERTY20) {
		toSerialize["CUSTOMPROPERTY20"] = o.CUSTOMPROPERTY20
	}
	if !IsNil(o.ROLENAME) {
		toSerialize["ROLENAME"] = o.ROLENAME
	}
	if !IsNil(o.HOMEPAGE) {
		toSerialize["HOMEPAGE"] = o.HOMEPAGE
	}
	if !IsNil(o.CUSTOMPROPERTY10) {
		toSerialize["CUSTOMPROPERTY10"] = o.CUSTOMPROPERTY10
	}
	if !IsNil(o.CUSTOMPROPERTY12) {
		toSerialize["CUSTOMPROPERTY12"] = o.CUSTOMPROPERTY12
	}
	if !IsNil(o.CUSTOMPROPERTY11) {
		toSerialize["CUSTOMPROPERTY11"] = o.CUSTOMPROPERTY11
	}
	if !IsNil(o.CUSTOMPROPERTY14) {
		toSerialize["CUSTOMPROPERTY14"] = o.CUSTOMPROPERTY14
	}
	if !IsNil(o.CUSTOMPROPERTY4) {
		toSerialize["CUSTOMPROPERTY4"] = o.CUSTOMPROPERTY4
	}
	if !IsNil(o.CUSTOMPROPERTY13) {
		toSerialize["CUSTOMPROPERTY13"] = o.CUSTOMPROPERTY13
	}
	if !IsNil(o.CUSTOMPROPERTY5) {
		toSerialize["CUSTOMPROPERTY5"] = o.CUSTOMPROPERTY5
	}
	if !IsNil(o.CUSTOMPROPERTY16) {
		toSerialize["CUSTOMPROPERTY16"] = o.CUSTOMPROPERTY16
	}
	if !IsNil(o.CUSTOMPROPERTY2) {
		toSerialize["CUSTOMPROPERTY2"] = o.CUSTOMPROPERTY2
	}
	if !IsNil(o.CUSTOMPROPERTY15) {
		toSerialize["CUSTOMPROPERTY15"] = o.CUSTOMPROPERTY15
	}
	if !IsNil(o.CUSTOMPROPERTY3) {
		toSerialize["CUSTOMPROPERTY3"] = o.CUSTOMPROPERTY3
	}
	if !IsNil(o.CUSTOMPROPERTY18) {
		toSerialize["CUSTOMPROPERTY18"] = o.CUSTOMPROPERTY18
	}
	if !IsNil(o.CUSTOMPROPERTY1) {
		toSerialize["CUSTOMPROPERTY1"] = o.CUSTOMPROPERTY1
	}
	if !IsNil(o.CUSTOMPROPERTY17) {
		toSerialize["CUSTOMPROPERTY17"] = o.CUSTOMPROPERTY17
	}
	if !IsNil(o.ROLEDESCRIPTION) {
		toSerialize["ROLEDESCRIPTION"] = o.ROLEDESCRIPTION
	}
	if !IsNil(o.CUSTOMPROPERTY19) {
		toSerialize["CUSTOMPROPERTY19"] = o.CUSTOMPROPERTY19
	}
	if !IsNil(o.ISOOTB) {
		toSerialize["ISOOTB"] = o.ISOOTB
	}
	if !IsNil(o.CUSTOMPROPERTY8) {
		toSerialize["CUSTOMPROPERTY8"] = o.CUSTOMPROPERTY8
	}
	if !IsNil(o.CUSTOMPROPERTY9) {
		toSerialize["CUSTOMPROPERTY9"] = o.CUSTOMPROPERTY9
	}
	if !IsNil(o.CUSTOMPROPERTY6) {
		toSerialize["CUSTOMPROPERTY6"] = o.CUSTOMPROPERTY6
	}
	if !IsNil(o.CUSTOMPROPERTY7) {
		toSerialize["CUSTOMPROPERTY7"] = o.CUSTOMPROPERTY7
	}
	if !IsNil(o.UPDATEDATE) {
		toSerialize["UPDATEDATE"] = o.UPDATEDATE
	}
	if !IsNil(o.READONLY) {
		toSerialize["READONLY"] = o.READONLY
	}
	if !IsNil(o.STATUSKEY) {
		toSerialize["STATUSKEY"] = o.STATUSKEY
	}
	return toSerialize, nil
}

type NullableSAVRole struct {
	value *SAVRole
	isSet bool
}

func (v NullableSAVRole) Get() *SAVRole {
	return v.value
}

func (v *NullableSAVRole) Set(val *SAVRole) {
	v.value = val
	v.isSet = true
}

func (v NullableSAVRole) IsSet() bool {
	return v.isSet
}

func (v *NullableSAVRole) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSAVRole(val *SAVRole) *NullableSAVRole {
	return &NullableSAVRole{value: val, isSet: true}
}

func (v NullableSAVRole) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSAVRole) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
