/*
Connection Management API

Use this API to create a connection in Saviynt Identity Cloud.  The Authorization header must have \"Bearer {token}\".  **Mandatory Parameters:** - **connectionname**: Specify the name to identify the connection. - **connectiontype**: Specify a connection type. For example, if your target application is Active Directory, specify the connection type as \"AD\".  **Optional Parameters:** - **description**: Provide a description for the connection. - **defaultsavroles**: Specify the SAV role(s) required for managing this connection along with its associated security systems, endpoints, accounts, and entitlements. - **emailTemplate**: Specify the email template applicable for notifications. - **sslCertificate**: Specify the SSL certificate(s) to secure the connection between EIC and the target application. - **vaultConfiguration**: Specify the path of the vault to obtain secret data (suffix the connector name to make it unique). - **saveinvault**: Set to true to save the encrypted attribute in the configured vault.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connections

import (
	"encoding/json"
)

// checks if the EntraIDConnectionAttributesConnectionTimeoutConfig type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &EntraIDConnectionAttributesConnectionTimeoutConfig{}

// EntraIDConnectionAttributesConnectionTimeoutConfig struct for EntraIDConnectionAttributesConnectionTimeoutConfig
type EntraIDConnectionAttributesConnectionTimeoutConfig struct {
	RetryWait *int32 `json:"retryWait,omitempty"`
	TokenRefreshMaxTryCount *int32 `json:"tokenRefreshMaxTryCount,omitempty"`
	RetryFailureStatusCode *string `json:"retryFailureStatusCode,omitempty"`
	RetryWaitMaxValue *int32 `json:"retryWaitMaxValue,omitempty"`
	RetryCount *int32 `json:"retryCount,omitempty"`
	ReadTimeout *int32 `json:"readTimeout,omitempty"`
	ConnectionTimeout *int32 `json:"connectionTimeout,omitempty"`
}

// NewEntraIDConnectionAttributesConnectionTimeoutConfig instantiates a new EntraIDConnectionAttributesConnectionTimeoutConfig object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewEntraIDConnectionAttributesConnectionTimeoutConfig() *EntraIDConnectionAttributesConnectionTimeoutConfig {
	this := EntraIDConnectionAttributesConnectionTimeoutConfig{}
	return &this
}

// NewEntraIDConnectionAttributesConnectionTimeoutConfigWithDefaults instantiates a new EntraIDConnectionAttributesConnectionTimeoutConfig object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewEntraIDConnectionAttributesConnectionTimeoutConfigWithDefaults() *EntraIDConnectionAttributesConnectionTimeoutConfig {
	this := EntraIDConnectionAttributesConnectionTimeoutConfig{}
	return &this
}

// GetRetryWait returns the RetryWait field value if set, zero value otherwise.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetRetryWait() int32 {
	if o == nil || IsNil(o.RetryWait) {
		var ret int32
		return ret
	}
	return *o.RetryWait
}

// GetRetryWaitOk returns a tuple with the RetryWait field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetRetryWaitOk() (*int32, bool) {
	if o == nil || IsNil(o.RetryWait) {
		return nil, false
	}
	return o.RetryWait, true
}

// HasRetryWait returns a boolean if a field has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) HasRetryWait() bool {
	if o != nil && !IsNil(o.RetryWait) {
		return true
	}

	return false
}

// SetRetryWait gets a reference to the given int32 and assigns it to the RetryWait field.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) SetRetryWait(v int32) {
	o.RetryWait = &v
}

// GetTokenRefreshMaxTryCount returns the TokenRefreshMaxTryCount field value if set, zero value otherwise.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetTokenRefreshMaxTryCount() int32 {
	if o == nil || IsNil(o.TokenRefreshMaxTryCount) {
		var ret int32
		return ret
	}
	return *o.TokenRefreshMaxTryCount
}

// GetTokenRefreshMaxTryCountOk returns a tuple with the TokenRefreshMaxTryCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetTokenRefreshMaxTryCountOk() (*int32, bool) {
	if o == nil || IsNil(o.TokenRefreshMaxTryCount) {
		return nil, false
	}
	return o.TokenRefreshMaxTryCount, true
}

// HasTokenRefreshMaxTryCount returns a boolean if a field has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) HasTokenRefreshMaxTryCount() bool {
	if o != nil && !IsNil(o.TokenRefreshMaxTryCount) {
		return true
	}

	return false
}

// SetTokenRefreshMaxTryCount gets a reference to the given int32 and assigns it to the TokenRefreshMaxTryCount field.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) SetTokenRefreshMaxTryCount(v int32) {
	o.TokenRefreshMaxTryCount = &v
}

// GetRetryFailureStatusCode returns the RetryFailureStatusCode field value if set, zero value otherwise.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetRetryFailureStatusCode() string {
	if o == nil || IsNil(o.RetryFailureStatusCode) {
		var ret string
		return ret
	}
	return *o.RetryFailureStatusCode
}

// GetRetryFailureStatusCodeOk returns a tuple with the RetryFailureStatusCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetRetryFailureStatusCodeOk() (*string, bool) {
	if o == nil || IsNil(o.RetryFailureStatusCode) {
		return nil, false
	}
	return o.RetryFailureStatusCode, true
}

// HasRetryFailureStatusCode returns a boolean if a field has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) HasRetryFailureStatusCode() bool {
	if o != nil && !IsNil(o.RetryFailureStatusCode) {
		return true
	}

	return false
}

// SetRetryFailureStatusCode gets a reference to the given string and assigns it to the RetryFailureStatusCode field.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) SetRetryFailureStatusCode(v string) {
	o.RetryFailureStatusCode = &v
}

// GetRetryWaitMaxValue returns the RetryWaitMaxValue field value if set, zero value otherwise.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetRetryWaitMaxValue() int32 {
	if o == nil || IsNil(o.RetryWaitMaxValue) {
		var ret int32
		return ret
	}
	return *o.RetryWaitMaxValue
}

// GetRetryWaitMaxValueOk returns a tuple with the RetryWaitMaxValue field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetRetryWaitMaxValueOk() (*int32, bool) {
	if o == nil || IsNil(o.RetryWaitMaxValue) {
		return nil, false
	}
	return o.RetryWaitMaxValue, true
}

// HasRetryWaitMaxValue returns a boolean if a field has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) HasRetryWaitMaxValue() bool {
	if o != nil && !IsNil(o.RetryWaitMaxValue) {
		return true
	}

	return false
}

// SetRetryWaitMaxValue gets a reference to the given int32 and assigns it to the RetryWaitMaxValue field.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) SetRetryWaitMaxValue(v int32) {
	o.RetryWaitMaxValue = &v
}

// GetRetryCount returns the RetryCount field value if set, zero value otherwise.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetRetryCount() int32 {
	if o == nil || IsNil(o.RetryCount) {
		var ret int32
		return ret
	}
	return *o.RetryCount
}

// GetRetryCountOk returns a tuple with the RetryCount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetRetryCountOk() (*int32, bool) {
	if o == nil || IsNil(o.RetryCount) {
		return nil, false
	}
	return o.RetryCount, true
}

// HasRetryCount returns a boolean if a field has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) HasRetryCount() bool {
	if o != nil && !IsNil(o.RetryCount) {
		return true
	}

	return false
}

// SetRetryCount gets a reference to the given int32 and assigns it to the RetryCount field.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) SetRetryCount(v int32) {
	o.RetryCount = &v
}

// GetReadTimeout returns the ReadTimeout field value if set, zero value otherwise.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetReadTimeout() int32 {
	if o == nil || IsNil(o.ReadTimeout) {
		var ret int32
		return ret
	}
	return *o.ReadTimeout
}

// GetReadTimeoutOk returns a tuple with the ReadTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetReadTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.ReadTimeout) {
		return nil, false
	}
	return o.ReadTimeout, true
}

// HasReadTimeout returns a boolean if a field has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) HasReadTimeout() bool {
	if o != nil && !IsNil(o.ReadTimeout) {
		return true
	}

	return false
}

// SetReadTimeout gets a reference to the given int32 and assigns it to the ReadTimeout field.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) SetReadTimeout(v int32) {
	o.ReadTimeout = &v
}

// GetConnectionTimeout returns the ConnectionTimeout field value if set, zero value otherwise.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetConnectionTimeout() int32 {
	if o == nil || IsNil(o.ConnectionTimeout) {
		var ret int32
		return ret
	}
	return *o.ConnectionTimeout
}

// GetConnectionTimeoutOk returns a tuple with the ConnectionTimeout field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) GetConnectionTimeoutOk() (*int32, bool) {
	if o == nil || IsNil(o.ConnectionTimeout) {
		return nil, false
	}
	return o.ConnectionTimeout, true
}

// HasConnectionTimeout returns a boolean if a field has been set.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) HasConnectionTimeout() bool {
	if o != nil && !IsNil(o.ConnectionTimeout) {
		return true
	}

	return false
}

// SetConnectionTimeout gets a reference to the given int32 and assigns it to the ConnectionTimeout field.
func (o *EntraIDConnectionAttributesConnectionTimeoutConfig) SetConnectionTimeout(v int32) {
	o.ConnectionTimeout = &v
}

func (o EntraIDConnectionAttributesConnectionTimeoutConfig) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o EntraIDConnectionAttributesConnectionTimeoutConfig) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RetryWait) {
		toSerialize["retryWait"] = o.RetryWait
	}
	if !IsNil(o.TokenRefreshMaxTryCount) {
		toSerialize["tokenRefreshMaxTryCount"] = o.TokenRefreshMaxTryCount
	}
	if !IsNil(o.RetryFailureStatusCode) {
		toSerialize["retryFailureStatusCode"] = o.RetryFailureStatusCode
	}
	if !IsNil(o.RetryWaitMaxValue) {
		toSerialize["retryWaitMaxValue"] = o.RetryWaitMaxValue
	}
	if !IsNil(o.RetryCount) {
		toSerialize["retryCount"] = o.RetryCount
	}
	if !IsNil(o.ReadTimeout) {
		toSerialize["readTimeout"] = o.ReadTimeout
	}
	if !IsNil(o.ConnectionTimeout) {
		toSerialize["connectionTimeout"] = o.ConnectionTimeout
	}
	return toSerialize, nil
}

type NullableEntraIDConnectionAttributesConnectionTimeoutConfig struct {
	value *EntraIDConnectionAttributesConnectionTimeoutConfig
	isSet bool
}

func (v NullableEntraIDConnectionAttributesConnectionTimeoutConfig) Get() *EntraIDConnectionAttributesConnectionTimeoutConfig {
	return v.value
}

func (v *NullableEntraIDConnectionAttributesConnectionTimeoutConfig) Set(val *EntraIDConnectionAttributesConnectionTimeoutConfig) {
	v.value = val
	v.isSet = true
}

func (v NullableEntraIDConnectionAttributesConnectionTimeoutConfig) IsSet() bool {
	return v.isSet
}

func (v *NullableEntraIDConnectionAttributesConnectionTimeoutConfig) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableEntraIDConnectionAttributesConnectionTimeoutConfig(val *EntraIDConnectionAttributesConnectionTimeoutConfig) *NullableEntraIDConnectionAttributesConnectionTimeoutConfig {
	return &NullableEntraIDConnectionAttributesConnectionTimeoutConfig{value: val, isSet: true}
}

func (v NullableEntraIDConnectionAttributesConnectionTimeoutConfig) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableEntraIDConnectionAttributesConnectionTimeoutConfig) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


