/*
testConnection Management API

Use this API to create a connection in Saviynt Identity Cloud.  The Authorization header must have \"Bearer {token}\".  **Mandatory Parameters:** - **connectionname**: Specify the name to identify the connection. - **connectiontype**: Specify a connection type. For example, if your target application is Active Directory, specify the connection type as \"AD\".  **Optional Parameters:** - **description**: Provide a description for the connection. - **defaultsavroles**: Specify the SAV role(s) required for managing this connection along with its associated security systems, endpoints, accounts, and entitlements. - **emailTemplate**: Specify the email template applicable for notifications. - **sslCertificate**: Specify the SSL certificate(s) to secure the connection between EIC and the target application. - **vaultConfiguration**: Specify the path of the vault to obtain secret data (suffix the connector name to make it unique). - **saveinvault**: Set to true to save the encrypted attribute in the configured vault.

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package connections

import (
	"encoding/json"
	"fmt"
	"gopkg.in/validator.v2"
)

// TestConnectionRequest - struct for TestConnectionRequest
type TestConnectionRequest struct {
	ADConnector *ADConnector
	ADSIConnector *ADSIConnector
	D365Connector *D365Connector
	RESTConnector *RESTConnector
	SAPConnector *SAPConnector
	SalesforceConnector *SalesforceConnector
	WorkdayConnector *WorkdayConnector
}

// ADConnectorAsTestConnectionRequest is a convenience function that returns ADConnector wrapped in TestConnectionRequest
func ADConnectorAsTestConnectionRequest(v *ADConnector) TestConnectionRequest {
	return TestConnectionRequest{
		ADConnector: v,
	}
}

// ADSIConnectorAsTestConnectionRequest is a convenience function that returns ADSIConnector wrapped in TestConnectionRequest
func ADSIConnectorAsTestConnectionRequest(v *ADSIConnector) TestConnectionRequest {
	return TestConnectionRequest{
		ADSIConnector: v,
	}
}

// D365ConnectorAsTestConnectionRequest is a convenience function that returns D365Connector wrapped in TestConnectionRequest
func D365ConnectorAsTestConnectionRequest(v *D365Connector) TestConnectionRequest {
	return TestConnectionRequest{
		D365Connector: v,
	}
}

// RESTConnectorAsTestConnectionRequest is a convenience function that returns RESTConnector wrapped in TestConnectionRequest
func RESTConnectorAsTestConnectionRequest(v *RESTConnector) TestConnectionRequest {
	return TestConnectionRequest{
		RESTConnector: v,
	}
}

// SAPConnectorAsTestConnectionRequest is a convenience function that returns SAPConnector wrapped in TestConnectionRequest
func SAPConnectorAsTestConnectionRequest(v *SAPConnector) TestConnectionRequest {
	return TestConnectionRequest{
		SAPConnector: v,
	}
}

// SalesforceConnectorAsTestConnectionRequest is a convenience function that returns SalesforceConnector wrapped in TestConnectionRequest
func SalesforceConnectorAsTestConnectionRequest(v *SalesforceConnector) TestConnectionRequest {
	return TestConnectionRequest{
		SalesforceConnector: v,
	}
}

// WorkdayConnectorAsTestConnectionRequest is a convenience function that returns WorkdayConnector wrapped in TestConnectionRequest
func WorkdayConnectorAsTestConnectionRequest(v *WorkdayConnector) TestConnectionRequest {
	return TestConnectionRequest{
		WorkdayConnector: v,
	}
}


// Unmarshal JSON data into one of the pointers in the struct
func (dst *TestConnectionRequest) UnmarshalJSON(data []byte) error {
	var err error
	match := 0
	// try to unmarshal data into ADConnector
	err = newStrictDecoder(data).Decode(&dst.ADConnector)
	if err == nil {
		jsonADConnector, _ := json.Marshal(dst.ADConnector)
		if string(jsonADConnector) == "{}" { // empty struct
			dst.ADConnector = nil
		} else {
			if err = validator.Validate(dst.ADConnector); err != nil {
				dst.ADConnector = nil
			} else {
				match++
			}
		}
	} else {
		dst.ADConnector = nil
	}

	// try to unmarshal data into ADSIConnector
	err = newStrictDecoder(data).Decode(&dst.ADSIConnector)
	if err == nil {
		jsonADSIConnector, _ := json.Marshal(dst.ADSIConnector)
		if string(jsonADSIConnector) == "{}" { // empty struct
			dst.ADSIConnector = nil
		} else {
			if err = validator.Validate(dst.ADSIConnector); err != nil {
				dst.ADSIConnector = nil
			} else {
				match++
			}
		}
	} else {
		dst.ADSIConnector = nil
	}

	// try to unmarshal data into D365Connector
	err = newStrictDecoder(data).Decode(&dst.D365Connector)
	if err == nil {
		jsonD365Connector, _ := json.Marshal(dst.D365Connector)
		if string(jsonD365Connector) == "{}" { // empty struct
			dst.D365Connector = nil
		} else {
			if err = validator.Validate(dst.D365Connector); err != nil {
				dst.D365Connector = nil
			} else {
				match++
			}
		}
	} else {
		dst.D365Connector = nil
	}

	// try to unmarshal data into RESTConnector
	err = newStrictDecoder(data).Decode(&dst.RESTConnector)
	if err == nil {
		jsonRESTConnector, _ := json.Marshal(dst.RESTConnector)
		if string(jsonRESTConnector) == "{}" { // empty struct
			dst.RESTConnector = nil
		} else {
			if err = validator.Validate(dst.RESTConnector); err != nil {
				dst.RESTConnector = nil
			} else {
				match++
			}
		}
	} else {
		dst.RESTConnector = nil
	}

	// try to unmarshal data into SAPConnector
	err = newStrictDecoder(data).Decode(&dst.SAPConnector)
	if err == nil {
		jsonSAPConnector, _ := json.Marshal(dst.SAPConnector)
		if string(jsonSAPConnector) == "{}" { // empty struct
			dst.SAPConnector = nil
		} else {
			if err = validator.Validate(dst.SAPConnector); err != nil {
				dst.SAPConnector = nil
			} else {
				match++
			}
		}
	} else {
		dst.SAPConnector = nil
	}

	// try to unmarshal data into SalesforceConnector
	err = newStrictDecoder(data).Decode(&dst.SalesforceConnector)
	if err == nil {
		jsonSalesforceConnector, _ := json.Marshal(dst.SalesforceConnector)
		if string(jsonSalesforceConnector) == "{}" { // empty struct
			dst.SalesforceConnector = nil
		} else {
			if err = validator.Validate(dst.SalesforceConnector); err != nil {
				dst.SalesforceConnector = nil
			} else {
				match++
			}
		}
	} else {
		dst.SalesforceConnector = nil
	}

	// try to unmarshal data into WorkdayConnector
	err = newStrictDecoder(data).Decode(&dst.WorkdayConnector)
	if err == nil {
		jsonWorkdayConnector, _ := json.Marshal(dst.WorkdayConnector)
		if string(jsonWorkdayConnector) == "{}" { // empty struct
			dst.WorkdayConnector = nil
		} else {
			if err = validator.Validate(dst.WorkdayConnector); err != nil {
				dst.WorkdayConnector = nil
			} else {
				match++
			}
		}
	} else {
		dst.WorkdayConnector = nil
	}

	if match > 1 { // more than 1 match
		// reset to nil
		dst.ADConnector = nil
		dst.ADSIConnector = nil
		dst.D365Connector = nil
		dst.RESTConnector = nil
		dst.SAPConnector = nil
		dst.SalesforceConnector = nil
		dst.WorkdayConnector = nil

		return fmt.Errorf("data matches more than one schema in oneOf(TestConnectionRequest)")
	} else if match == 1 {
		return nil // exactly one match
	} else { // no match
		return fmt.Errorf("data failed to match schemas in oneOf(TestConnectionRequest)")
	}
}

// Marshal data from the first non-nil pointers in the struct to JSON
func (src TestConnectionRequest) MarshalJSON() ([]byte, error) {
	if src.ADConnector != nil {
		return json.Marshal(&src.ADConnector)
	}

	if src.ADSIConnector != nil {
		return json.Marshal(&src.ADSIConnector)
	}

	if src.D365Connector != nil {
		return json.Marshal(&src.D365Connector)
	}

	if src.RESTConnector != nil {
		return json.Marshal(&src.RESTConnector)
	}

	if src.SAPConnector != nil {
		return json.Marshal(&src.SAPConnector)
	}

	if src.SalesforceConnector != nil {
		return json.Marshal(&src.SalesforceConnector)
	}

	if src.WorkdayConnector != nil {
		return json.Marshal(&src.WorkdayConnector)
	}

	return nil, nil // no data in oneOf schemas
}

// Get the actual instance
func (obj *TestConnectionRequest) GetActualInstance() (interface{}) {
	if obj == nil {
		return nil
	}
	if obj.ADConnector != nil {
		return obj.ADConnector
	}

	if obj.ADSIConnector != nil {
		return obj.ADSIConnector
	}

	if obj.D365Connector != nil {
		return obj.D365Connector
	}

	if obj.RESTConnector != nil {
		return obj.RESTConnector
	}

	if obj.SAPConnector != nil {
		return obj.SAPConnector
	}

	if obj.SalesforceConnector != nil {
		return obj.SalesforceConnector
	}

	if obj.WorkdayConnector != nil {
		return obj.WorkdayConnector
	}

	// all schemas are nil
	return nil
}

// Get the actual instance value
func (obj TestConnectionRequest) GetActualInstanceValue() (interface{}) {
	if obj.ADConnector != nil {
		return *obj.ADConnector
	}

	if obj.ADSIConnector != nil {
		return *obj.ADSIConnector
	}

	if obj.D365Connector != nil {
		return *obj.D365Connector
	}

	if obj.RESTConnector != nil {
		return *obj.RESTConnector
	}

	if obj.SAPConnector != nil {
		return *obj.SAPConnector
	}

	if obj.SalesforceConnector != nil {
		return *obj.SalesforceConnector
	}

	if obj.WorkdayConnector != nil {
		return *obj.WorkdayConnector
	}

	// all schemas are nil
	return nil
}

type NullableTestConnectionRequest struct {
	value *TestConnectionRequest
	isSet bool
}

func (v NullableTestConnectionRequest) Get() *TestConnectionRequest {
	return v.value
}

func (v *NullableTestConnectionRequest) Set(val *TestConnectionRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableTestConnectionRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableTestConnectionRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableTestConnectionRequest(val *TestConnectionRequest) *NullableTestConnectionRequest {
	return &NullableTestConnectionRequest{value: val, isSet: true}
}

func (v NullableTestConnectionRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableTestConnectionRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


