/*
Organization Management API

API for creating, updating, retrieving, and deleting organization data in EIC

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the CreateOrganizationRequestOwnersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &CreateOrganizationRequestOwnersInner{}

// CreateOrganizationRequestOwnersInner struct for CreateOrganizationRequestOwnersInner
type CreateOrganizationRequestOwnersInner struct {
	Owner *string `json:"owner,omitempty"`
	Rank *int32 `json:"rank,omitempty"`
}

// NewCreateOrganizationRequestOwnersInner instantiates a new CreateOrganizationRequestOwnersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewCreateOrganizationRequestOwnersInner() *CreateOrganizationRequestOwnersInner {
	this := CreateOrganizationRequestOwnersInner{}
	return &this
}

// NewCreateOrganizationRequestOwnersInnerWithDefaults instantiates a new CreateOrganizationRequestOwnersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewCreateOrganizationRequestOwnersInnerWithDefaults() *CreateOrganizationRequestOwnersInner {
	this := CreateOrganizationRequestOwnersInner{}
	return &this
}

// GetOwner returns the Owner field value if set, zero value otherwise.
func (o *CreateOrganizationRequestOwnersInner) GetOwner() string {
	if o == nil || IsNil(o.Owner) {
		var ret string
		return ret
	}
	return *o.Owner
}

// GetOwnerOk returns a tuple with the Owner field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationRequestOwnersInner) GetOwnerOk() (*string, bool) {
	if o == nil || IsNil(o.Owner) {
		return nil, false
	}
	return o.Owner, true
}

// HasOwner returns a boolean if a field has been set.
func (o *CreateOrganizationRequestOwnersInner) HasOwner() bool {
	if o != nil && !IsNil(o.Owner) {
		return true
	}

	return false
}

// SetOwner gets a reference to the given string and assigns it to the Owner field.
func (o *CreateOrganizationRequestOwnersInner) SetOwner(v string) {
	o.Owner = &v
}

// GetRank returns the Rank field value if set, zero value otherwise.
func (o *CreateOrganizationRequestOwnersInner) GetRank() int32 {
	if o == nil || IsNil(o.Rank) {
		var ret int32
		return ret
	}
	return *o.Rank
}

// GetRankOk returns a tuple with the Rank field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *CreateOrganizationRequestOwnersInner) GetRankOk() (*int32, bool) {
	if o == nil || IsNil(o.Rank) {
		return nil, false
	}
	return o.Rank, true
}

// HasRank returns a boolean if a field has been set.
func (o *CreateOrganizationRequestOwnersInner) HasRank() bool {
	if o != nil && !IsNil(o.Rank) {
		return true
	}

	return false
}

// SetRank gets a reference to the given int32 and assigns it to the Rank field.
func (o *CreateOrganizationRequestOwnersInner) SetRank(v int32) {
	o.Rank = &v
}

func (o CreateOrganizationRequestOwnersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o CreateOrganizationRequestOwnersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Owner) {
		toSerialize["owner"] = o.Owner
	}
	if !IsNil(o.Rank) {
		toSerialize["rank"] = o.Rank
	}
	return toSerialize, nil
}

type NullableCreateOrganizationRequestOwnersInner struct {
	value *CreateOrganizationRequestOwnersInner
	isSet bool
}

func (v NullableCreateOrganizationRequestOwnersInner) Get() *CreateOrganizationRequestOwnersInner {
	return v.value
}

func (v *NullableCreateOrganizationRequestOwnersInner) Set(val *CreateOrganizationRequestOwnersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableCreateOrganizationRequestOwnersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableCreateOrganizationRequestOwnersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableCreateOrganizationRequestOwnersInner(val *CreateOrganizationRequestOwnersInner) *NullableCreateOrganizationRequestOwnersInner {
	return &NullableCreateOrganizationRequestOwnersInner{value: val, isSet: true}
}

func (v NullableCreateOrganizationRequestOwnersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableCreateOrganizationRequestOwnersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


