/*
Organization Management API

API for creating, updating, retrieving, and deleting organization data in EIC

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the UpdateOrganizationRequestUsersInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &UpdateOrganizationRequestUsersInner{}

// UpdateOrganizationRequestUsersInner struct for UpdateOrganizationRequestUsersInner
type UpdateOrganizationRequestUsersInner struct {
	Username *string `json:"username,omitempty"`
	Updatetype *string `json:"updatetype,omitempty"`
}

// NewUpdateOrganizationRequestUsersInner instantiates a new UpdateOrganizationRequestUsersInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateOrganizationRequestUsersInner() *UpdateOrganizationRequestUsersInner {
	this := UpdateOrganizationRequestUsersInner{}
	return &this
}

// NewUpdateOrganizationRequestUsersInnerWithDefaults instantiates a new UpdateOrganizationRequestUsersInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateOrganizationRequestUsersInnerWithDefaults() *UpdateOrganizationRequestUsersInner {
	this := UpdateOrganizationRequestUsersInner{}
	return &this
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *UpdateOrganizationRequestUsersInner) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationRequestUsersInner) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *UpdateOrganizationRequestUsersInner) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *UpdateOrganizationRequestUsersInner) SetUsername(v string) {
	o.Username = &v
}

// GetUpdatetype returns the Updatetype field value if set, zero value otherwise.
func (o *UpdateOrganizationRequestUsersInner) GetUpdatetype() string {
	if o == nil || IsNil(o.Updatetype) {
		var ret string
		return ret
	}
	return *o.Updatetype
}

// GetUpdatetypeOk returns a tuple with the Updatetype field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *UpdateOrganizationRequestUsersInner) GetUpdatetypeOk() (*string, bool) {
	if o == nil || IsNil(o.Updatetype) {
		return nil, false
	}
	return o.Updatetype, true
}

// HasUpdatetype returns a boolean if a field has been set.
func (o *UpdateOrganizationRequestUsersInner) HasUpdatetype() bool {
	if o != nil && !IsNil(o.Updatetype) {
		return true
	}

	return false
}

// SetUpdatetype gets a reference to the given string and assigns it to the Updatetype field.
func (o *UpdateOrganizationRequestUsersInner) SetUpdatetype(v string) {
	o.Updatetype = &v
}

func (o UpdateOrganizationRequestUsersInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o UpdateOrganizationRequestUsersInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	if !IsNil(o.Updatetype) {
		toSerialize["updatetype"] = o.Updatetype
	}
	return toSerialize, nil
}

type NullableUpdateOrganizationRequestUsersInner struct {
	value *UpdateOrganizationRequestUsersInner
	isSet bool
}

func (v NullableUpdateOrganizationRequestUsersInner) Get() *UpdateOrganizationRequestUsersInner {
	return v.value
}

func (v *NullableUpdateOrganizationRequestUsersInner) Set(val *UpdateOrganizationRequestUsersInner) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateOrganizationRequestUsersInner) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateOrganizationRequestUsersInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateOrganizationRequestUsersInner(val *UpdateOrganizationRequestUsersInner) *NullableUpdateOrganizationRequestUsersInner {
	return &NullableUpdateOrganizationRequestUsersInner{value: val, isSet: true}
}

func (v NullableUpdateOrganizationRequestUsersInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateOrganizationRequestUsersInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


