/*
Organization Management API

API for creating, updating, retrieving, and deleting organization data in EIC

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetOrganizationUserDetails200Response type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetOrganizationUserDetails200Response{}

// GetOrganizationUserDetails200Response struct for GetOrganizationUserDetails200Response
type GetOrganizationUserDetails200Response struct {
	Displaycount *int32 `json:"displaycount,omitempty"`
	Msg *string `json:"msg,omitempty"`
	Totalcount *int32 `json:"totalcount,omitempty"`
	Offset *int32 `json:"offset,omitempty"`
	Max *int32 `json:"max,omitempty"`
	Organizations []GetOrganizationUserDetails200ResponseOrganizationsInner `json:"organizations,omitempty"`
	ErrorCode *string `json:"errorCode,omitempty"`
	Username *string `json:"username,omitempty"`
}

// NewGetOrganizationUserDetails200Response instantiates a new GetOrganizationUserDetails200Response object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetOrganizationUserDetails200Response() *GetOrganizationUserDetails200Response {
	this := GetOrganizationUserDetails200Response{}
	return &this
}

// NewGetOrganizationUserDetails200ResponseWithDefaults instantiates a new GetOrganizationUserDetails200Response object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetOrganizationUserDetails200ResponseWithDefaults() *GetOrganizationUserDetails200Response {
	this := GetOrganizationUserDetails200Response{}
	return &this
}

// GetDisplaycount returns the Displaycount field value if set, zero value otherwise.
func (o *GetOrganizationUserDetails200Response) GetDisplaycount() int32 {
	if o == nil || IsNil(o.Displaycount) {
		var ret int32
		return ret
	}
	return *o.Displaycount
}

// GetDisplaycountOk returns a tuple with the Displaycount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationUserDetails200Response) GetDisplaycountOk() (*int32, bool) {
	if o == nil || IsNil(o.Displaycount) {
		return nil, false
	}
	return o.Displaycount, true
}

// HasDisplaycount returns a boolean if a field has been set.
func (o *GetOrganizationUserDetails200Response) HasDisplaycount() bool {
	if o != nil && !IsNil(o.Displaycount) {
		return true
	}

	return false
}

// SetDisplaycount gets a reference to the given int32 and assigns it to the Displaycount field.
func (o *GetOrganizationUserDetails200Response) SetDisplaycount(v int32) {
	o.Displaycount = &v
}

// GetMsg returns the Msg field value if set, zero value otherwise.
func (o *GetOrganizationUserDetails200Response) GetMsg() string {
	if o == nil || IsNil(o.Msg) {
		var ret string
		return ret
	}
	return *o.Msg
}

// GetMsgOk returns a tuple with the Msg field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationUserDetails200Response) GetMsgOk() (*string, bool) {
	if o == nil || IsNil(o.Msg) {
		return nil, false
	}
	return o.Msg, true
}

// HasMsg returns a boolean if a field has been set.
func (o *GetOrganizationUserDetails200Response) HasMsg() bool {
	if o != nil && !IsNil(o.Msg) {
		return true
	}

	return false
}

// SetMsg gets a reference to the given string and assigns it to the Msg field.
func (o *GetOrganizationUserDetails200Response) SetMsg(v string) {
	o.Msg = &v
}

// GetTotalcount returns the Totalcount field value if set, zero value otherwise.
func (o *GetOrganizationUserDetails200Response) GetTotalcount() int32 {
	if o == nil || IsNil(o.Totalcount) {
		var ret int32
		return ret
	}
	return *o.Totalcount
}

// GetTotalcountOk returns a tuple with the Totalcount field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationUserDetails200Response) GetTotalcountOk() (*int32, bool) {
	if o == nil || IsNil(o.Totalcount) {
		return nil, false
	}
	return o.Totalcount, true
}

// HasTotalcount returns a boolean if a field has been set.
func (o *GetOrganizationUserDetails200Response) HasTotalcount() bool {
	if o != nil && !IsNil(o.Totalcount) {
		return true
	}

	return false
}

// SetTotalcount gets a reference to the given int32 and assigns it to the Totalcount field.
func (o *GetOrganizationUserDetails200Response) SetTotalcount(v int32) {
	o.Totalcount = &v
}

// GetOffset returns the Offset field value if set, zero value otherwise.
func (o *GetOrganizationUserDetails200Response) GetOffset() int32 {
	if o == nil || IsNil(o.Offset) {
		var ret int32
		return ret
	}
	return *o.Offset
}

// GetOffsetOk returns a tuple with the Offset field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationUserDetails200Response) GetOffsetOk() (*int32, bool) {
	if o == nil || IsNil(o.Offset) {
		return nil, false
	}
	return o.Offset, true
}

// HasOffset returns a boolean if a field has been set.
func (o *GetOrganizationUserDetails200Response) HasOffset() bool {
	if o != nil && !IsNil(o.Offset) {
		return true
	}

	return false
}

// SetOffset gets a reference to the given int32 and assigns it to the Offset field.
func (o *GetOrganizationUserDetails200Response) SetOffset(v int32) {
	o.Offset = &v
}

// GetMax returns the Max field value if set, zero value otherwise.
func (o *GetOrganizationUserDetails200Response) GetMax() int32 {
	if o == nil || IsNil(o.Max) {
		var ret int32
		return ret
	}
	return *o.Max
}

// GetMaxOk returns a tuple with the Max field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationUserDetails200Response) GetMaxOk() (*int32, bool) {
	if o == nil || IsNil(o.Max) {
		return nil, false
	}
	return o.Max, true
}

// HasMax returns a boolean if a field has been set.
func (o *GetOrganizationUserDetails200Response) HasMax() bool {
	if o != nil && !IsNil(o.Max) {
		return true
	}

	return false
}

// SetMax gets a reference to the given int32 and assigns it to the Max field.
func (o *GetOrganizationUserDetails200Response) SetMax(v int32) {
	o.Max = &v
}

// GetOrganizations returns the Organizations field value if set, zero value otherwise.
func (o *GetOrganizationUserDetails200Response) GetOrganizations() []GetOrganizationUserDetails200ResponseOrganizationsInner {
	if o == nil || IsNil(o.Organizations) {
		var ret []GetOrganizationUserDetails200ResponseOrganizationsInner
		return ret
	}
	return o.Organizations
}

// GetOrganizationsOk returns a tuple with the Organizations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationUserDetails200Response) GetOrganizationsOk() ([]GetOrganizationUserDetails200ResponseOrganizationsInner, bool) {
	if o == nil || IsNil(o.Organizations) {
		return nil, false
	}
	return o.Organizations, true
}

// HasOrganizations returns a boolean if a field has been set.
func (o *GetOrganizationUserDetails200Response) HasOrganizations() bool {
	if o != nil && !IsNil(o.Organizations) {
		return true
	}

	return false
}

// SetOrganizations gets a reference to the given []GetOrganizationUserDetails200ResponseOrganizationsInner and assigns it to the Organizations field.
func (o *GetOrganizationUserDetails200Response) SetOrganizations(v []GetOrganizationUserDetails200ResponseOrganizationsInner) {
	o.Organizations = v
}

// GetErrorCode returns the ErrorCode field value if set, zero value otherwise.
func (o *GetOrganizationUserDetails200Response) GetErrorCode() string {
	if o == nil || IsNil(o.ErrorCode) {
		var ret string
		return ret
	}
	return *o.ErrorCode
}

// GetErrorCodeOk returns a tuple with the ErrorCode field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationUserDetails200Response) GetErrorCodeOk() (*string, bool) {
	if o == nil || IsNil(o.ErrorCode) {
		return nil, false
	}
	return o.ErrorCode, true
}

// HasErrorCode returns a boolean if a field has been set.
func (o *GetOrganizationUserDetails200Response) HasErrorCode() bool {
	if o != nil && !IsNil(o.ErrorCode) {
		return true
	}

	return false
}

// SetErrorCode gets a reference to the given string and assigns it to the ErrorCode field.
func (o *GetOrganizationUserDetails200Response) SetErrorCode(v string) {
	o.ErrorCode = &v
}

// GetUsername returns the Username field value if set, zero value otherwise.
func (o *GetOrganizationUserDetails200Response) GetUsername() string {
	if o == nil || IsNil(o.Username) {
		var ret string
		return ret
	}
	return *o.Username
}

// GetUsernameOk returns a tuple with the Username field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetOrganizationUserDetails200Response) GetUsernameOk() (*string, bool) {
	if o == nil || IsNil(o.Username) {
		return nil, false
	}
	return o.Username, true
}

// HasUsername returns a boolean if a field has been set.
func (o *GetOrganizationUserDetails200Response) HasUsername() bool {
	if o != nil && !IsNil(o.Username) {
		return true
	}

	return false
}

// SetUsername gets a reference to the given string and assigns it to the Username field.
func (o *GetOrganizationUserDetails200Response) SetUsername(v string) {
	o.Username = &v
}

func (o GetOrganizationUserDetails200Response) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetOrganizationUserDetails200Response) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Displaycount) {
		toSerialize["displaycount"] = o.Displaycount
	}
	if !IsNil(o.Msg) {
		toSerialize["msg"] = o.Msg
	}
	if !IsNil(o.Totalcount) {
		toSerialize["totalcount"] = o.Totalcount
	}
	if !IsNil(o.Offset) {
		toSerialize["offset"] = o.Offset
	}
	if !IsNil(o.Max) {
		toSerialize["max"] = o.Max
	}
	if !IsNil(o.Organizations) {
		toSerialize["organizations"] = o.Organizations
	}
	if !IsNil(o.ErrorCode) {
		toSerialize["errorCode"] = o.ErrorCode
	}
	if !IsNil(o.Username) {
		toSerialize["username"] = o.Username
	}
	return toSerialize, nil
}

type NullableGetOrganizationUserDetails200Response struct {
	value *GetOrganizationUserDetails200Response
	isSet bool
}

func (v NullableGetOrganizationUserDetails200Response) Get() *GetOrganizationUserDetails200Response {
	return v.value
}

func (v *NullableGetOrganizationUserDetails200Response) Set(val *GetOrganizationUserDetails200Response) {
	v.value = val
	v.isSet = true
}

func (v NullableGetOrganizationUserDetails200Response) IsSet() bool {
	return v.isSet
}

func (v *NullableGetOrganizationUserDetails200Response) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetOrganizationUserDetails200Response(val *GetOrganizationUserDetails200Response) *NullableGetOrganizationUserDetails200Response {
	return &NullableGetOrganizationUserDetails200Response{value: val, isSet: true}
}

func (v NullableGetOrganizationUserDetails200Response) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetOrganizationUserDetails200Response) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


