/*
Entitlements Management API

Testing EntitlementsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/saviynt/saviynt-api-go-client/entitlements"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func StringPtr(s string) *string {
	return &s
}
func Test_openapi_EntitlementsAPIService(t *testing.T) {

	cfg := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(cfg)
	ctx := context.Background()

	// Test GetEntitlements
	t.Run("Test GetEntitlements without parameters", func(t *testing.T) {
		t.Skip("skip test")
		resp, httpRes, err := apiClient.EntitlementsAPI.GetEntitlements(ctx).Execute()
		require.NoError(t, err, "Unexpected error in GetEntitlements API")
		require.NotNil(t, resp, "Response should not be nil")
		assert.Equal(t, 200, httpRes.StatusCode, "Expected HTTP status 200")
	})

	// Test GetChildEntitlements
	t.Run("Test GetChildEntitlements", func(t *testing.T) {
		t.Skip("skip test")
		resp, httpRes, err := apiClient.EntitlementsAPI.GetChildEntitlements(ctx).
			Endpointname("AD_Rashid").
			Max(5).
			Offset(0).
			Execute()

		require.NoError(t, err, "Unexpected error in GetChildEntitlements API")
		require.NotNil(t, resp, "Response should not be nil")
		assert.Equal(t, 200, httpRes.StatusCode, "Expected HTTP status 200")
	})

	// Test CreateUpdateEntitlement
	t.Run("Test CreateUpdateEntitlement", func(t *testing.T) {
		t.Skip("skip test")
		NewValue := "CN=adtestrequest123,OU=DocTeamOU,OU=SaviyntTeams,DC=saviyntlabs,DC=org1"
		createReq := openapiclient.CreateUpdateEntitlementRequest{
			Endpoint:            "AD_Rashid",
			Entitlementtype:     "memberOf",
			EntitlementValue:    "CN=adtestrequest123,OU=DocTeamOU,OU=SaviyntTeams,DC=saviyntlabs,DC=org",
			NewEntitlementValue: &NewValue,
		}
		resp, httpRes, err := apiClient.EntitlementsAPI.CreateUpdateEntitlement(ctx).
			CreateUpdateEntitlementRequest(createReq).
			Execute()

		require.NoError(t, err, "Unexpected error in CreateUpdateEntitlement API")
		require.NotNil(t, resp, "Response should not be nil")
		assert.Equal(t, 200, httpRes.StatusCode, "Expected HTTP status 200")
	})

	// Test GetEntitlementValuesForEndpoint
	t.Run("Test GetEntitlementValuesForEndpoint", func(t *testing.T) {
		t.Skip("skip test")
		getReq := openapiclient.GetEntitlementValuesForEndpointRequest{
			Endpoint:        "AD_Rashid",
			EntitlementType: openapiclient.PtrString("memberOf"), // Optional field
		}
		resp, httpRes, err := apiClient.EntitlementsAPI.GetEntitlementValuesForEndpoint(ctx).GetEntitlementValuesForEndpointRequest(getReq).Execute()

		require.NoError(t, err, "Unexpected error in GetEntitlementValuesForEndpoint API")
		require.NotNil(t, resp, "Response should not be nil")
		assert.Equal(t, 200, httpRes.StatusCode, "Expected HTTP status 200")
	})

	// Test GetListOfPrivileges
	t.Run("Test GetListOfPrivileges", func(t *testing.T) {
		t.Skip("skip test")
		resp, httpRes, err := apiClient.EntitlementsAPI.GetListOfPrivilegesForEntitlementType(ctx).
			Endpoint("AD_Rashid").
			Entitlementtype("memberOf").
			Execute()

		require.NoError(t, err, "Unexpected error in GetListOfPrivileges API")
		require.NotNil(t, resp, "Response should not be nil")
		assert.Equal(t, 200, httpRes.StatusCode, "Expected HTTP status 200")
	})

	// Test RemoveEntitlementFromRole
	t.Run("Test RemoveEntitlementFromRole", func(t *testing.T) {
		t.Skip("skip test")
		entitlement_value := "CN=adtestrequest123,OU=DocTeamOU,OU=SaviyntTeams,DC=saviyntlabs,DC=org"
		entitlement_type := "memberOf"
		entitlment_endpoint := "AD_Rashid"
		req := openapiclient.RemoveEntitlementFromRoleRequest{
			Requestor: StringPtr("admin"),
			Rolename:  StringPtr("Harshit Verma"),
			Entitlements: []openapiclient.RemoveEntitlementFromRoleRequestEntitlementsInner{
				{
					Entitlementvalue: entitlement_value,
					Entitlementtype:  entitlement_type,
					Endpoint:         entitlment_endpoint,
				},
			},
		}

		resp, httpRes, err := apiClient.EntitlementsAPI.RemoveEntitlementFromRole(ctx).
			RemoveEntitlementFromRoleRequest(req).
			Execute()

		require.NoError(t, err, "Unexpected error in RemoveEntitlementFromRole API")
		require.NotNil(t, resp, "Response should not be nil")
		assert.Equal(t, 200, httpRes.StatusCode, "Expected HTTP status 200")
	})

}
