/*
Organization Management API

Testing OrganizationsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"encoding/json"
	"fmt"
	"log"
	"testing"

	openapi "github.com/saviynt/saviynt-api-go-client/organization"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func marshalResp(v interface{}) []byte {
	b, err := json.MarshalIndent(v, "", "  ")
	if err != nil {
		log.Fatalf("Error marshalling response: %v", err)
	}
	return b
}

var (
	apiClient       *openapi.APIClient
	ctx             context.Context
	defaultUsername = "awsadmin"
	defaultOrgName  = "TestOrg8"
	comment         = "Hello this is from test connections"
)

func Test_openapi_OrganizationsAPIService(t *testing.T) {

	cfg := openapi.NewConfiguration()
	apiClient = openapi.NewAPIClient(cfg)
	ctx = context.Background()
	t.Run("Test OrganizationsAPIService CreateOrganization", func(t *testing.T) {
		t.Skip("skip test")
		createReq := openapi.CreateOrganizationRequest{
			Organizationname: defaultOrgName,
			Username:         defaultUsername,
		}
		createReq.SetPrimarycontact("awsadmin")
		createReq.SetComments("Created via CreateOrganization test")

		resp, httpRes, err := apiClient.OrganizationsAPI.
			CreateOrganization(ctx).
			CreateOrganizationRequest(createReq).
			Execute()
		require.NoError(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

		fmt.Println("CreateOrganization Response:")
		fmt.Println(string(marshalResp(resp)))
	})

	t.Run("Test OrganizationsAPIService UpdateOrganization", func(t *testing.T) {
		t.Skip("skip test")
		updateReq := openapi.UpdateOrganizationRequest{
			Organizationname: defaultOrgName,
			Username:         defaultUsername,
			Comments:         &comment,
		}
		updateReq.SetComments("Updated via UpdateOrganization test")
		resp, httpRes, err := apiClient.OrganizationsAPI.
			UpdateOrganization(ctx).
			UpdateOrganizationRequest(updateReq).
			Execute()
		require.NoError(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

		fmt.Println("UpdateOrganization Response:")
		fmt.Println(string(marshalResp(resp)))
	})
	t.Run("Test OrganizationsAPIService GetOrganization", func(t *testing.T) {
		t.Skip("skip test")
		getReq := openapi.GetOrganizationRequest{
			Organizationname: &defaultOrgName,
		}

		// Call the GetOrganization API endpoint.
		resp, httpRes, err := apiClient.OrganizationsAPI.
			GetOrganization(ctx).
			GetOrganizationRequest(getReq).
			Execute()
		require.NoError(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

		// Marshal the response for readability and print it.
		respJSON, err := json.MarshalIndent(resp, "", "  ")
		require.NoError(t, err)
		fmt.Printf("HTTP status: %d\nResponse JSON:\n%s\n", httpRes.StatusCode, string(respJSON))
	})

	t.Run("Test OrganizationsAPIService GetOrganizationUserDetails", func(t *testing.T) {
		t.Skip("skip test")
		getDetailsReq := openapi.GetOrganizationUserDetailsRequest{
			Username: defaultUsername,
		}
		resp, httpRes, err := apiClient.OrganizationsAPI.
			GetOrganizationUserDetails(ctx).
			GetOrganizationUserDetailsRequest(getDetailsReq).
			Execute()
		require.NoError(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

		fmt.Println("GetOrganizationUserDetails Response:")
		fmt.Println(string(marshalResp(resp)))
	})

	t.Run("Test OrganizationsAPIService DeleteOrganization", func(t *testing.T) {
		t.Skip("skip test")
		deleteReq := openapi.DeleteOrganizationRequest{
			Organizationname: &defaultOrgName,
			Username:         &defaultUsername,
		}
		resp, httpRes, err := apiClient.OrganizationsAPI.
			DeleteOrganization(ctx).
			DeleteOrganizationRequest(deleteReq).
			Execute()
		require.NoError(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

		fmt.Println("DeleteOrganization Response:")
		fmt.Println(string(marshalResp(resp)))
	})

	t.Run("Test OrganizationsAPIService UpdateOrganizationUsers", func(t *testing.T) {
		t.Skip("skip test")
		organizationName := "TestOrg5"
		username := "Customer101C"
		updatetype := "remove"
		// Create an UpdateOrganizationUsersRequest.
		updateUsersReq := openapi.UpdateOrganizationUsersRequest{
			Organizationname: &organizationName,
			Users: []openapi.UpdateOrganizationUsersRequestUsersInner{
				{
					Username:   &username,
					Updatetype: &updatetype,
				},
			},
		}
		resp, httpRes, err := apiClient.OrganizationsAPI.
			UpdateOrganizationUsers(ctx).
			UpdateOrganizationUsersRequest(updateUsersReq).
			Execute()
		require.NoError(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

		fmt.Println("UpdateOrganizationUsers Response:")
		fmt.Println(string(marshalResp(resp)))
	})

}
