/*
Saviynt Delegated Administration API

Deglated Administration

API version: 1.0
Contact: https://github.com/saviynt
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package delegatedadministration

import (
	"encoding/json"
	"bytes"
	"fmt"
)

// checks if the Delegate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &Delegate{}

// Delegate Delegate represents a Deleate returne dfrom the Fetch Eisting Delegates List API.
type Delegate struct {
	Delegatekey string `json:"delegatekey"`
	Name string `json:"name"`
	Description string `json:"description"`
	Parentusername string `json:"parentusername"`
	ParentFirstName *string `json:"parentFirstName,omitempty"`
	ParentLastName *string `json:"parentLastName,omitempty"`
	DelegateFirstName *string `json:"delegateFirstName,omitempty"`
	DelegateLastName *string `json:"delegateLastName,omitempty"`
	Status string `json:"status"`
	Delegateusername string `json:"delegateusername"`
	// date format 07/14/2020
	Startdate string `json:"startdate"`
	// date with format 07/14/2020
	Enddate string `json:"enddate"`
}

type _Delegate Delegate

// NewDelegate instantiates a new Delegate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewDelegate(delegatekey string, name string, description string, parentusername string, status string, delegateusername string, startdate string, enddate string) *Delegate {
	this := Delegate{}
	this.Delegatekey = delegatekey
	this.Name = name
	this.Description = description
	this.Parentusername = parentusername
	this.Status = status
	this.Delegateusername = delegateusername
	this.Startdate = startdate
	this.Enddate = enddate
	return &this
}

// NewDelegateWithDefaults instantiates a new Delegate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewDelegateWithDefaults() *Delegate {
	this := Delegate{}
	return &this
}

// GetDelegatekey returns the Delegatekey field value
func (o *Delegate) GetDelegatekey() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Delegatekey
}

// GetDelegatekeyOk returns a tuple with the Delegatekey field value
// and a boolean to check if the value has been set.
func (o *Delegate) GetDelegatekeyOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delegatekey, true
}

// SetDelegatekey sets field value
func (o *Delegate) SetDelegatekey(v string) {
	o.Delegatekey = v
}

// GetName returns the Name field value
func (o *Delegate) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *Delegate) GetNameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *Delegate) SetName(v string) {
	o.Name = v
}

// GetDescription returns the Description field value
func (o *Delegate) GetDescription() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Description
}

// GetDescriptionOk returns a tuple with the Description field value
// and a boolean to check if the value has been set.
func (o *Delegate) GetDescriptionOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Description, true
}

// SetDescription sets field value
func (o *Delegate) SetDescription(v string) {
	o.Description = v
}

// GetParentusername returns the Parentusername field value
func (o *Delegate) GetParentusername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Parentusername
}

// GetParentusernameOk returns a tuple with the Parentusername field value
// and a boolean to check if the value has been set.
func (o *Delegate) GetParentusernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Parentusername, true
}

// SetParentusername sets field value
func (o *Delegate) SetParentusername(v string) {
	o.Parentusername = v
}

// GetParentFirstName returns the ParentFirstName field value if set, zero value otherwise.
func (o *Delegate) GetParentFirstName() string {
	if o == nil || IsNil(o.ParentFirstName) {
		var ret string
		return ret
	}
	return *o.ParentFirstName
}

// GetParentFirstNameOk returns a tuple with the ParentFirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delegate) GetParentFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.ParentFirstName) {
		return nil, false
	}
	return o.ParentFirstName, true
}

// HasParentFirstName returns a boolean if a field has been set.
func (o *Delegate) HasParentFirstName() bool {
	if o != nil && !IsNil(o.ParentFirstName) {
		return true
	}

	return false
}

// SetParentFirstName gets a reference to the given string and assigns it to the ParentFirstName field.
func (o *Delegate) SetParentFirstName(v string) {
	o.ParentFirstName = &v
}

// GetParentLastName returns the ParentLastName field value if set, zero value otherwise.
func (o *Delegate) GetParentLastName() string {
	if o == nil || IsNil(o.ParentLastName) {
		var ret string
		return ret
	}
	return *o.ParentLastName
}

// GetParentLastNameOk returns a tuple with the ParentLastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delegate) GetParentLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.ParentLastName) {
		return nil, false
	}
	return o.ParentLastName, true
}

// HasParentLastName returns a boolean if a field has been set.
func (o *Delegate) HasParentLastName() bool {
	if o != nil && !IsNil(o.ParentLastName) {
		return true
	}

	return false
}

// SetParentLastName gets a reference to the given string and assigns it to the ParentLastName field.
func (o *Delegate) SetParentLastName(v string) {
	o.ParentLastName = &v
}

// GetDelegateFirstName returns the DelegateFirstName field value if set, zero value otherwise.
func (o *Delegate) GetDelegateFirstName() string {
	if o == nil || IsNil(o.DelegateFirstName) {
		var ret string
		return ret
	}
	return *o.DelegateFirstName
}

// GetDelegateFirstNameOk returns a tuple with the DelegateFirstName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delegate) GetDelegateFirstNameOk() (*string, bool) {
	if o == nil || IsNil(o.DelegateFirstName) {
		return nil, false
	}
	return o.DelegateFirstName, true
}

// HasDelegateFirstName returns a boolean if a field has been set.
func (o *Delegate) HasDelegateFirstName() bool {
	if o != nil && !IsNil(o.DelegateFirstName) {
		return true
	}

	return false
}

// SetDelegateFirstName gets a reference to the given string and assigns it to the DelegateFirstName field.
func (o *Delegate) SetDelegateFirstName(v string) {
	o.DelegateFirstName = &v
}

// GetDelegateLastName returns the DelegateLastName field value if set, zero value otherwise.
func (o *Delegate) GetDelegateLastName() string {
	if o == nil || IsNil(o.DelegateLastName) {
		var ret string
		return ret
	}
	return *o.DelegateLastName
}

// GetDelegateLastNameOk returns a tuple with the DelegateLastName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *Delegate) GetDelegateLastNameOk() (*string, bool) {
	if o == nil || IsNil(o.DelegateLastName) {
		return nil, false
	}
	return o.DelegateLastName, true
}

// HasDelegateLastName returns a boolean if a field has been set.
func (o *Delegate) HasDelegateLastName() bool {
	if o != nil && !IsNil(o.DelegateLastName) {
		return true
	}

	return false
}

// SetDelegateLastName gets a reference to the given string and assigns it to the DelegateLastName field.
func (o *Delegate) SetDelegateLastName(v string) {
	o.DelegateLastName = &v
}

// GetStatus returns the Status field value
func (o *Delegate) GetStatus() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Status
}

// GetStatusOk returns a tuple with the Status field value
// and a boolean to check if the value has been set.
func (o *Delegate) GetStatusOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Status, true
}

// SetStatus sets field value
func (o *Delegate) SetStatus(v string) {
	o.Status = v
}

// GetDelegateusername returns the Delegateusername field value
func (o *Delegate) GetDelegateusername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Delegateusername
}

// GetDelegateusernameOk returns a tuple with the Delegateusername field value
// and a boolean to check if the value has been set.
func (o *Delegate) GetDelegateusernameOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Delegateusername, true
}

// SetDelegateusername sets field value
func (o *Delegate) SetDelegateusername(v string) {
	o.Delegateusername = v
}

// GetStartdate returns the Startdate field value
func (o *Delegate) GetStartdate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Startdate
}

// GetStartdateOk returns a tuple with the Startdate field value
// and a boolean to check if the value has been set.
func (o *Delegate) GetStartdateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Startdate, true
}

// SetStartdate sets field value
func (o *Delegate) SetStartdate(v string) {
	o.Startdate = v
}

// GetEnddate returns the Enddate field value
func (o *Delegate) GetEnddate() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Enddate
}

// GetEnddateOk returns a tuple with the Enddate field value
// and a boolean to check if the value has been set.
func (o *Delegate) GetEnddateOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Enddate, true
}

// SetEnddate sets field value
func (o *Delegate) SetEnddate(v string) {
	o.Enddate = v
}

func (o Delegate) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o Delegate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["delegatekey"] = o.Delegatekey
	toSerialize["name"] = o.Name
	toSerialize["description"] = o.Description
	toSerialize["parentusername"] = o.Parentusername
	if !IsNil(o.ParentFirstName) {
		toSerialize["parentFirstName"] = o.ParentFirstName
	}
	if !IsNil(o.ParentLastName) {
		toSerialize["parentLastName"] = o.ParentLastName
	}
	if !IsNil(o.DelegateFirstName) {
		toSerialize["delegateFirstName"] = o.DelegateFirstName
	}
	if !IsNil(o.DelegateLastName) {
		toSerialize["delegateLastName"] = o.DelegateLastName
	}
	toSerialize["status"] = o.Status
	toSerialize["delegateusername"] = o.Delegateusername
	toSerialize["startdate"] = o.Startdate
	toSerialize["enddate"] = o.Enddate
	return toSerialize, nil
}

func (o *Delegate) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"delegatekey",
		"name",
		"description",
		"parentusername",
		"status",
		"delegateusername",
		"startdate",
		"enddate",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err;
	}

	for _, requiredProperty := range(requiredProperties) {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varDelegate := _Delegate{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varDelegate)

	if err != nil {
		return err
	}

	*o = Delegate(varDelegate)

	return err
}

type NullableDelegate struct {
	value *Delegate
	isSet bool
}

func (v NullableDelegate) Get() *Delegate {
	return v.value
}

func (v *NullableDelegate) Set(val *Delegate) {
	v.value = val
	v.isSet = true
}

func (v NullableDelegate) IsSet() bool {
	return v.isSet
}

func (v *NullableDelegate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableDelegate(val *Delegate) *NullableDelegate {
	return &NullableDelegate{value: val, isSet: true}
}

func (v NullableDelegate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableDelegate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


