/*
Connection Management API

Testing ConnectionsAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package connections

import (
	"context"
	openapiclient "github.com/saviynt/saviynt-api-go-client/connections"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"log"
	"testing"
)

func Test_connections_ConnectionsAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ConnectionsAPIService CreateOrUpdate", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		data := "4060"
		req := openapiclient.GetConnectionDetailsRequest{
			Connectionkey: &data,
		}
		resp, httpRes, err := apiClient.ConnectionsAPI.GetConnectionDetails(context.Background()).GetConnectionDetailsRequest(req).Execute()
		if err != nil {
			log.Fatalf("API error: %v", err.Error())
		}

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)
		// respJSON, err := json.MarshalIndent(resp, "", "  ")
		// if err != nil {
		// 	log.Fatalf("Error marshalling response: %v", err)
		// }
		// fmt.Println("Export Connection Response:")
		// fmt.Println(string(respJSON))
	})

}
