/*
Entitlements Management API

API for creating, updating, retrieving, and deleting Entitlements data in EIC

API version: 1.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner{}

// GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner struct for GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner
type GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner struct {
	AddDependentTask *string `json:"addDependentTask,omitempty"`
	Description *string `json:"description,omitempty"`
	ExcludeEntitlement *string `json:"excludeEntitlement,omitempty"`
	ExportPrimary *string `json:"exportPrimary,omitempty"`
	Primary *string `json:"primary,omitempty"`
	PrimaryEntKey *string `json:"primaryEntKey,omitempty"`
	PrimaryEntType *string `json:"primaryEntType,omitempty"`
	RemoveDependentEntTask *string `json:"removeDependentEntTask,omitempty"`
	RequestFilter *string `json:"requestFilter,omitempty"`
}

// NewGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner instantiates a new GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner() *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner {
	this := GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner{}
	return &this
}

// NewGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInnerWithDefaults instantiates a new GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInnerWithDefaults() *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner {
	this := GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner{}
	return &this
}

// GetAddDependentTask returns the AddDependentTask field value if set, zero value otherwise.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetAddDependentTask() string {
	if o == nil || IsNil(o.AddDependentTask) {
		var ret string
		return ret
	}
	return *o.AddDependentTask
}

// GetAddDependentTaskOk returns a tuple with the AddDependentTask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetAddDependentTaskOk() (*string, bool) {
	if o == nil || IsNil(o.AddDependentTask) {
		return nil, false
	}
	return o.AddDependentTask, true
}

// HasAddDependentTask returns a boolean if a field has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) HasAddDependentTask() bool {
	if o != nil && !IsNil(o.AddDependentTask) {
		return true
	}

	return false
}

// SetAddDependentTask gets a reference to the given string and assigns it to the AddDependentTask field.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) SetAddDependentTask(v string) {
	o.AddDependentTask = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) SetDescription(v string) {
	o.Description = &v
}

// GetExcludeEntitlement returns the ExcludeEntitlement field value if set, zero value otherwise.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetExcludeEntitlement() string {
	if o == nil || IsNil(o.ExcludeEntitlement) {
		var ret string
		return ret
	}
	return *o.ExcludeEntitlement
}

// GetExcludeEntitlementOk returns a tuple with the ExcludeEntitlement field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetExcludeEntitlementOk() (*string, bool) {
	if o == nil || IsNil(o.ExcludeEntitlement) {
		return nil, false
	}
	return o.ExcludeEntitlement, true
}

// HasExcludeEntitlement returns a boolean if a field has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) HasExcludeEntitlement() bool {
	if o != nil && !IsNil(o.ExcludeEntitlement) {
		return true
	}

	return false
}

// SetExcludeEntitlement gets a reference to the given string and assigns it to the ExcludeEntitlement field.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) SetExcludeEntitlement(v string) {
	o.ExcludeEntitlement = &v
}

// GetExportPrimary returns the ExportPrimary field value if set, zero value otherwise.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetExportPrimary() string {
	if o == nil || IsNil(o.ExportPrimary) {
		var ret string
		return ret
	}
	return *o.ExportPrimary
}

// GetExportPrimaryOk returns a tuple with the ExportPrimary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetExportPrimaryOk() (*string, bool) {
	if o == nil || IsNil(o.ExportPrimary) {
		return nil, false
	}
	return o.ExportPrimary, true
}

// HasExportPrimary returns a boolean if a field has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) HasExportPrimary() bool {
	if o != nil && !IsNil(o.ExportPrimary) {
		return true
	}

	return false
}

// SetExportPrimary gets a reference to the given string and assigns it to the ExportPrimary field.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) SetExportPrimary(v string) {
	o.ExportPrimary = &v
}

// GetPrimary returns the Primary field value if set, zero value otherwise.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetPrimary() string {
	if o == nil || IsNil(o.Primary) {
		var ret string
		return ret
	}
	return *o.Primary
}

// GetPrimaryOk returns a tuple with the Primary field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetPrimaryOk() (*string, bool) {
	if o == nil || IsNil(o.Primary) {
		return nil, false
	}
	return o.Primary, true
}

// HasPrimary returns a boolean if a field has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) HasPrimary() bool {
	if o != nil && !IsNil(o.Primary) {
		return true
	}

	return false
}

// SetPrimary gets a reference to the given string and assigns it to the Primary field.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) SetPrimary(v string) {
	o.Primary = &v
}

// GetPrimaryEntKey returns the PrimaryEntKey field value if set, zero value otherwise.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetPrimaryEntKey() string {
	if o == nil || IsNil(o.PrimaryEntKey) {
		var ret string
		return ret
	}
	return *o.PrimaryEntKey
}

// GetPrimaryEntKeyOk returns a tuple with the PrimaryEntKey field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetPrimaryEntKeyOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryEntKey) {
		return nil, false
	}
	return o.PrimaryEntKey, true
}

// HasPrimaryEntKey returns a boolean if a field has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) HasPrimaryEntKey() bool {
	if o != nil && !IsNil(o.PrimaryEntKey) {
		return true
	}

	return false
}

// SetPrimaryEntKey gets a reference to the given string and assigns it to the PrimaryEntKey field.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) SetPrimaryEntKey(v string) {
	o.PrimaryEntKey = &v
}

// GetPrimaryEntType returns the PrimaryEntType field value if set, zero value otherwise.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetPrimaryEntType() string {
	if o == nil || IsNil(o.PrimaryEntType) {
		var ret string
		return ret
	}
	return *o.PrimaryEntType
}

// GetPrimaryEntTypeOk returns a tuple with the PrimaryEntType field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetPrimaryEntTypeOk() (*string, bool) {
	if o == nil || IsNil(o.PrimaryEntType) {
		return nil, false
	}
	return o.PrimaryEntType, true
}

// HasPrimaryEntType returns a boolean if a field has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) HasPrimaryEntType() bool {
	if o != nil && !IsNil(o.PrimaryEntType) {
		return true
	}

	return false
}

// SetPrimaryEntType gets a reference to the given string and assigns it to the PrimaryEntType field.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) SetPrimaryEntType(v string) {
	o.PrimaryEntType = &v
}

// GetRemoveDependentEntTask returns the RemoveDependentEntTask field value if set, zero value otherwise.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetRemoveDependentEntTask() string {
	if o == nil || IsNil(o.RemoveDependentEntTask) {
		var ret string
		return ret
	}
	return *o.RemoveDependentEntTask
}

// GetRemoveDependentEntTaskOk returns a tuple with the RemoveDependentEntTask field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetRemoveDependentEntTaskOk() (*string, bool) {
	if o == nil || IsNil(o.RemoveDependentEntTask) {
		return nil, false
	}
	return o.RemoveDependentEntTask, true
}

// HasRemoveDependentEntTask returns a boolean if a field has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) HasRemoveDependentEntTask() bool {
	if o != nil && !IsNil(o.RemoveDependentEntTask) {
		return true
	}

	return false
}

// SetRemoveDependentEntTask gets a reference to the given string and assigns it to the RemoveDependentEntTask field.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) SetRemoveDependentEntTask(v string) {
	o.RemoveDependentEntTask = &v
}

// GetRequestFilter returns the RequestFilter field value if set, zero value otherwise.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetRequestFilter() string {
	if o == nil || IsNil(o.RequestFilter) {
		var ret string
		return ret
	}
	return *o.RequestFilter
}

// GetRequestFilterOk returns a tuple with the RequestFilter field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) GetRequestFilterOk() (*string, bool) {
	if o == nil || IsNil(o.RequestFilter) {
		return nil, false
	}
	return o.RequestFilter, true
}

// HasRequestFilter returns a boolean if a field has been set.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) HasRequestFilter() bool {
	if o != nil && !IsNil(o.RequestFilter) {
		return true
	}

	return false
}

// SetRequestFilter gets a reference to the given string and assigns it to the RequestFilter field.
func (o *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) SetRequestFilter(v string) {
	o.RequestFilter = &v
}

func (o GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) MarshalJSON() ([]byte, error) {
	toSerialize,err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.AddDependentTask) {
		toSerialize["addDependentTask"] = o.AddDependentTask
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.ExcludeEntitlement) {
		toSerialize["excludeEntitlement"] = o.ExcludeEntitlement
	}
	if !IsNil(o.ExportPrimary) {
		toSerialize["exportPrimary"] = o.ExportPrimary
	}
	if !IsNil(o.Primary) {
		toSerialize["primary"] = o.Primary
	}
	if !IsNil(o.PrimaryEntKey) {
		toSerialize["primaryEntKey"] = o.PrimaryEntKey
	}
	if !IsNil(o.PrimaryEntType) {
		toSerialize["primaryEntType"] = o.PrimaryEntType
	}
	if !IsNil(o.RemoveDependentEntTask) {
		toSerialize["removeDependentEntTask"] = o.RemoveDependentEntTask
	}
	if !IsNil(o.RequestFilter) {
		toSerialize["requestFilter"] = o.RequestFilter
	}
	return toSerialize, nil
}

type NullableGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner struct {
	value *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner
	isSet bool
}

func (v NullableGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) Get() *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner {
	return v.value
}

func (v *NullableGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) Set(val *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) {
	v.value = val
	v.isSet = true
}

func (v NullableGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) IsSet() bool {
	return v.isSet
}

func (v *NullableGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner(val *GetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) *NullableGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner {
	return &NullableGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner{value: val, isSet: true}
}

func (v NullableGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableGetEntitlements200ResponseEntitlementdetailsInnerEntitlementMapDetailsInner) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


